-- HerdHarbor member-to-member animal and pedigree transfers.
-- Direct browser access is intentionally denied; authenticated users interact
-- through the animal-transfer Edge Function, which authorizes every action.

create table if not exists public.herdharbor_member_transfer_identity (
  user_id uuid primary key references auth.users(id) on delete cascade,
  transfer_code text not null unique default ('HH-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))),
  email_normalized text not null,
  display_name text not null default 'HerdHarbor member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint herdharbor_member_transfer_identity_code_check check (transfer_code ~ '^HH-[A-Z0-9]{10}$')
);

create unique index if not exists herdharbor_member_transfer_identity_email_idx
  on public.herdharbor_member_transfer_identity (lower(email_normalized));

create table if not exists public.herdharbor_direct_animal_transfers (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  transfer_id text not null,
  source_sale_number text not null default '',
  sale_date text not null default '',
  status text not null default 'pending',
  payload_version integer not null default 1,
  payload jsonb not null,
  subject_count integer not null default 1,
  subject_names text[] not null default '{}',
  pedigree_record_count integer not null default 1,
  includes_genetics boolean not null default false,
  sender_display_name text not null default 'HerdHarbor member',
  recipient_display_name text not null default 'HerdHarbor member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  accepted_at timestamptz,
  declined_at timestamptz,
  cancelled_at timestamptz,
  constraint herdharbor_direct_transfer_status_check check (status in ('pending','accepted','declined','cancelled')),
  constraint herdharbor_direct_transfer_sender_recipient_check check (sender_id <> recipient_id),
  constraint herdharbor_direct_transfer_transfer_id_check check (char_length(transfer_id) between 1 and 120),
  constraint herdharbor_direct_transfer_payload_check check (jsonb_typeof(payload) = 'object'),
  constraint herdharbor_direct_transfer_subject_count_check check (subject_count between 1 and 25),
  constraint herdharbor_direct_transfer_pedigree_count_check check (pedigree_record_count between 1 and 100)
);

create unique index if not exists herdharbor_direct_transfer_one_open_idx
  on public.herdharbor_direct_animal_transfers (sender_id, transfer_id)
  where status in ('pending','accepted');

create index if not exists herdharbor_direct_transfer_recipient_inbox_idx
  on public.herdharbor_direct_animal_transfers (recipient_id, status, created_at desc);

create index if not exists herdharbor_direct_transfer_sender_outbox_idx
  on public.herdharbor_direct_animal_transfers (sender_id, created_at desc);

create table if not exists public.herdharbor_direct_transfer_events (
  id bigint generated by default as identity primary key,
  transfer_row_id uuid not null references public.herdharbor_direct_animal_transfers(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  created_at timestamptz not null default now(),
  constraint herdharbor_direct_transfer_event_type_check check (event_type in ('created','previewed','prepared','accepted','declined','cancelled'))
);

create index if not exists herdharbor_direct_transfer_events_transfer_idx
  on public.herdharbor_direct_transfer_events (transfer_row_id, created_at);

alter table public.herdharbor_member_transfer_identity enable row level security;
alter table public.herdharbor_direct_animal_transfers enable row level security;
alter table public.herdharbor_direct_transfer_events enable row level security;

revoke all on table public.herdharbor_member_transfer_identity from anon, authenticated;
revoke all on table public.herdharbor_direct_animal_transfers from anon, authenticated;
revoke all on table public.herdharbor_direct_transfer_events from anon, authenticated;
revoke all on sequence public.herdharbor_direct_transfer_events_id_seq from anon, authenticated;

grant all on table public.herdharbor_member_transfer_identity to service_role;
grant all on table public.herdharbor_direct_animal_transfers to service_role;
grant all on table public.herdharbor_direct_transfer_events to service_role;
grant usage, select on sequence public.herdharbor_direct_transfer_events_id_seq to service_role;

create or replace function public.herdharbor_direct_transfer_resolve(lookup_value text)
returns table (
  recipient_id uuid,
  member_code text,
  display_name text,
  masked_email text
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  lookup_clean text := trim(coalesce(lookup_value, ''));
  target_id uuid;
  target_email text;
  target_name text;
begin
  if lookup_clean = '' or char_length(lookup_clean) > 320 then
    return;
  end if;

  if upper(lookup_clean) ~ '^HH-[A-Z0-9]{10}$' then
    select i.user_id into target_id
    from public.herdharbor_member_transfer_identity i
    where upper(i.transfer_code) = upper(lookup_clean)
    limit 1;
  else
    select u.id into target_id
    from auth.users u
    where lower(u.email) = lower(lookup_clean)
    limit 1;
  end if;

  if target_id is null then
    return;
  end if;

  select lower(coalesce(u.email, '')),
         coalesce(
           nullif(h.app_state #>> '{profile,operationName}', ''),
           nullif(r.organization_name, ''),
           nullif(u.raw_user_meta_data ->> 'full_name', ''),
           nullif(u.raw_user_meta_data ->> 'name', ''),
           'HerdHarbor member'
         )
    into target_email, target_name
  from auth.users u
  left join public.herdharbor_user_data h on h.user_id = u.id
  left join public.registration_profiles r on r.user_id = u.id
  where u.id = target_id;

  insert into public.herdharbor_member_transfer_identity (user_id, email_normalized, display_name, updated_at)
  values (target_id, target_email, target_name, now())
  on conflict (user_id) do update set
    email_normalized = excluded.email_normalized,
    display_name = excluded.display_name,
    updated_at = now();

  return query
  select i.user_id,
         i.transfer_code,
         i.display_name,
         case
           when position('@' in i.email_normalized) > 1
             then left(i.email_normalized, 1) || '***@' || split_part(i.email_normalized, '@', 2)
           else 'HerdHarbor member'
         end
  from public.herdharbor_member_transfer_identity i
  where i.user_id = target_id;
end;
$$;

revoke all on function public.herdharbor_direct_transfer_resolve(text) from public, anon, authenticated;
grant execute on function public.herdharbor_direct_transfer_resolve(text) to service_role;

comment on table public.herdharbor_direct_animal_transfers is
  'Secure pending/accepted member-to-member transfers. Payloads contain only animal identity, pedigree, structured transferable genetics, and provenance.';
comment on function public.herdharbor_direct_transfer_resolve(text) is
  'Service-role-only recipient resolver for email or HH member transfer code. Never exposed directly to browser roles.';
