(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.HerdHarborBreedingIntelligenceCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='1.5.1';
const EVIDENCE_STATUS=Object.freeze({CONFIRMED:'confirmed',INFERRED:'inferred',POSSIBLE:'possible',UNKNOWN:'unknown'});
const PRIORITY={unknown:0,possible:1,inferred:2,confirmed:3};
const MODULES=Object.create(null);
const TERMS={Rabbit:{male:'Buck',female:'Doe',birth:'Kindling',offspring:'Kits',group:'Litter'},Cattle:{male:'Bull',female:'Cow/Heifer',birth:'Calving',offspring:'Calves',group:'Calving'},Goats:{male:'Buck',female:'Doe',birth:'Kidding',offspring:'Kids',group:'Kidding'},Sheep:{male:'Ram',female:'Ewe',birth:'Lambing',offspring:'Lambs',group:'Lambing'},Poultry:{male:'Rooster/Cock',female:'Hen',birth:'Hatch',offspring:'Chicks',group:'Hatch'},Horses:{male:'Stallion',female:'Mare',birth:'Foaling',offspring:'Foals',group:'Foaling'},Swine:{male:'Boar',female:'Sow/Gilt',birth:'Farrowing',offspring:'Piglets',group:'Litter'},Dogs:{male:'Sire',female:'Dam',birth:'Whelping',offspring:'Puppies',group:'Litter'}};
const RABBIT_LOCI=Object.freeze({A:{name:'Agouti pattern',dominance:['A','at','a']},B:{name:'Black / chocolate pigment',dominance:['B','b']},C:{name:'Color expression',dominance:['C','cchd','cchl','ch','c']},D:{name:'Dense / dilute',dominance:['D','d']},E:{name:'Extension',dominance:['Ed','Es','E','ej','e']}});
const clean=v=>String(v==null?'':v).trim();
function canonicalSpecies(v){const s=clean(v).toLowerCase();if(/^(rabbit|rabbits)$/.test(s))return'Rabbit';if(/^(cattle|cow|cows)$/.test(s))return'Cattle';if(/^(goat|goats)$/.test(s))return'Goats';if(s==='sheep')return'Sheep';if(/^(poultry|chicken|chickens)$/.test(s))return'Poultry';if(/^(horse|horses)$/.test(s))return'Horses';if(/^(swine|pig|pigs)$/.test(s))return'Swine';if(/^(dog|dogs)$/.test(s))return'Dogs';return clean(v)||'Other';}
const speciesTerms=s=>TERMS[canonicalSpecies(s)]||{male:'Sire',female:'Dam',birth:'Birth',offspring:'Offspring',group:'Birth record'};
function registerSpeciesModule(name,module){if(!name||!module)throw new Error('A species module name and object are required.');MODULES[canonicalSpecies(name)]=Object.freeze({...module});return MODULES[canonicalSpecies(name)];}
const getSpeciesModule=name=>MODULES[canonicalSpecies(name)]||null;
const rank=(l,a)=>{const i=RABBIT_LOCI[l].dominance.indexOf(a);return i<0?999:i;};
function sortPair(l,p){const a=Array.isArray(p)?p.slice(0,2):['_','_'];while(a.length<2)a.push('_');return a.sort((x,y)=>x==='_'?1:y==='_'?-1:rank(l,x)-rank(l,y));}
const pairKey=(l,p)=>sortPair(l,p).join('/');
const known=p=>Array.isArray(p)&&p.length===2&&p.every(a=>a&&a!=='_');
const dominant=(l,p)=>{const a=(p||[]).filter(x=>x&&x!=='_').sort((x,y)=>rank(l,x)-rank(l,y));return a[0]||'_';};
function allPairs(l){const a=RABBIT_LOCI[l].dominance,o=[];for(let i=0;i<a.length;i++)for(let j=i;j<a.length;j++)o.push([a[i],a[j]]);return o;}
function matches(l,pattern){if(!Array.isArray(pattern)||pattern.length!==2)return allPairs(l);return allPairs(l).filter(p=>{const s=sortPair(l,p);return [[s[0],s[1]],[s[1],s[0]]].some(x=>pattern.every((t,i)=>t==='_'||t===x[i]));});}
const COLOR={
'black':{A:[['a','a']],B:[['B','_']],C:[['C','_']],D:[['D','_']],E:[['Ed','_'],['Es','_'],['E','_']]},
'blue':{A:[['a','a']],B:[['B','_']],C:[['C','_']],D:[['d','d']],E:[['Ed','_'],['Es','_'],['E','_']]},
'chocolate':{A:[['a','a']],B:[['b','b']],C:[['C','_']],D:[['D','_']],E:[['Ed','_'],['Es','_'],['E','_']]},
'lilac':{A:[['a','a']],B:[['b','b']],C:[['C','_']],D:[['d','d']],E:[['Ed','_'],['Es','_'],['E','_']]},
'chestnut':{A:[['A','_']],B:[['B','_']],C:[['C','_']],D:[['D','_']],E:[['E','_']]},
'chestnut agouti':{A:[['A','_']],B:[['B','_']],C:[['C','_']],D:[['D','_']],E:[['E','_']]},
'opal':{A:[['A','_']],B:[['B','_']],C:[['C','_']],D:[['d','d']],E:[['E','_']]},
'chocolate agouti':{A:[['A','_']],B:[['b','b']],C:[['C','_']],D:[['D','_']],E:[['E','_']]},
'lynx':{A:[['A','_']],B:[['b','b']],C:[['C','_']],D:[['d','d']],E:[['E','_']]},
'black otter':{A:[['at','_']],B:[['B','_']],C:[['C','_']],D:[['D','_']],E:[['E','_']]},
'blue otter':{A:[['at','_']],B:[['B','_']],C:[['C','_']],D:[['d','d']],E:[['E','_']]},
'chocolate otter':{A:[['at','_']],B:[['b','b']],C:[['C','_']],D:[['D','_']],E:[['E','_']]},
'lilac otter':{A:[['at','_']],B:[['b','b']],C:[['C','_']],D:[['d','d']],E:[['E','_']]},
'black tort':{A:[['a','a']],B:[['B','_']],C:[['C','_']],D:[['D','_']],E:[['e','e']]},
'blue tort':{A:[['a','a']],B:[['B','_']],C:[['C','_']],D:[['d','d']],E:[['e','e']]},
'chocolate tort':{A:[['a','a']],B:[['b','b']],C:[['C','_']],D:[['D','_']],E:[['e','e']]},
'lilac tort':{A:[['a','a']],B:[['b','b']],C:[['C','_']],D:[['d','d']],E:[['e','e']]},
'rew':{C:[['c','c']]},'red eyed white':{C:[['c','c']]},'red-eyed white':{C:[['c','c']]},
'pointed white':{C:[['ch','ch'],['ch','c']]},'himalayan':{C:[['ch','ch'],['ch','c']]},'californian':{C:[['ch','ch'],['ch','c']]}
};
const normColor=c=>clean(c).toLowerCase().replace(/\s+/g,' ');
const colorConstraints=c=>COLOR[normColor(c)]||null;
function patternLabelForColor(c){const x=colorConstraints(c);if(!x)return'No validated core A/B/C/D/E pattern is mapped for this recorded color.';return Object.keys(RABBIT_LOCI).map(l=>x[l]?`${l}:${x[l].map(p=>p.join('')).join(' or ')}`:`${l}_/_`).join(' · ');}
function normalizeGenetics(g){const s=g&&typeof g==='object'?g:{},loci={};Object.keys(RABBIT_LOCI).forEach(l=>{const r=s.loci?.[l];let p=Array.isArray(r)?r:r?.alleles;p=sortPair(l,Array.isArray(p)?p:['_','_']);loci[l]={alleles:p,status:r?.status||'unknown',source:r?.source||'',note:r?.note||''};});return{version:1,species:'Rabbit',loci,evidence:Array.isArray(s.evidence)?s.evidence.slice():[],tests:Array.isArray(s.tests)?s.tests.slice():[],conflicts:Array.isArray(s.conflicts)?s.conflicts.slice():[],updatedAt:s.updatedAt||null};}
function possiblePairsForLocus(profile,color,l){const g=normalizeGenetics(profile?.genetics),explicit=g.loci[l].alleles;let c=allPairs(l);if(explicit.some(a=>a&&a!=='_'))c=matches(l,explicit);const rule=colorConstraints(color);if(rule?.[l]){const allowed=new Set();rule[l].forEach(p=>matches(l,p).forEach(x=>allowed.add(pairKey(l,x))));const f=c.filter(x=>allowed.has(pairKey(l,x)));if(f.length)c=f;}return c;}
function gametes(p){if(!known(p))return null;return p[0]===p[1]?new Map([[p[0],1]]):new Map([[p[0],.5],[p[1],.5]]);}
function crossLocus(l,p1,p2){const a=gametes(sortPair(l,p1)),b=gametes(sortPair(l,p2));if(!a||!b)return{exact:false,outcomes:[]};const m=new Map();a.forEach((pa,x)=>b.forEach((pb,y)=>{const p=sortPair(l,[x,y]),k=pairKey(l,p);m.set(k,(m.get(k)||0)+pa*pb);}));return{exact:true,outcomes:[...m].map(([k,probability])=>({alleles:k.split('/'),probability}))};}
function pigment(B,D){const choc=B[0]==='b'&&B[1]==='b',dil=D[0]==='d'&&D[1]==='d';return choc&&dil?'Lilac':choc?'Chocolate':dil?'Blue':'Black';}
function phenotypeFromGenotype(g){const A=sortPair('A',g.A),B=sortPair('B',g.B),C=sortPair('C',g.C),D=sortPair('D',g.D),E=sortPair('E',g.E);if(![A,B,C,D,E].every(known))return{name:'Unknown',family:'Unknown',scope:'core'};if(C[0]==='c'&&C[1]==='c')return{name:'REW',family:'Red-eyed white',scope:'core A/B/C/D/E'};const p=pigment(B,D),e=dominant('E',E);if(e==='Ed')return{name:p,family:'Full-extension',scope:'core A/B/C/D/E'};const c=dominant('C',C);if(c==='ch')return{name:'Pointed White family',family:'Himalayan/Pointed White',scope:'core A/B/C/D/E'};if(c==='cchl')return{name:'Shaded family',family:'Shaded',scope:'core A/B/C/D/E'};if(c==='cchd')return{name:'Chinchilla family',family:'Chinchilla',scope:'core A/B/C/D/E'};const a=dominant('A',A);if(E[0]==='e'&&E[1]==='e'){if(a==='a')return{name:`${p} Tort`,family:'Tortoiseshell',scope:'core A/B/C/D/E'};if(a==='A')return{name:'Orange/Fawn family',family:'Non-extension agouti',scope:'modifier-dependent'};return{name:'Non-extension tan-pattern family',family:'Non-extension',scope:'modifier-dependent'};}if(e==='ej')return{name:'Harlequin family',family:'Harlequin/Japanese',scope:'modifier-dependent'};if(e==='Es'&&a==='A')return{name:'Steel family',family:'Steel',scope:'modifier-dependent'};if(a==='A'){const n={Black:'Chestnut Agouti',Blue:'Opal',Chocolate:'Chocolate Agouti',Lilac:'Lynx'};return{name:n[p],family:'Agouti',scope:'core A/B/C/D/E'};}if(a==='at')return{name:`${p} Otter`,family:'Tan pattern',scope:'core A/B/C/D/E'};return{name:p,family:'Self',scope:'core A/B/C/D/E'};}
function exactCross(p1,p2){const results={};for(const l of Object.keys(RABBIT_LOCI)){const a=normalizeGenetics(p1?.genetics).loci[l].alleles,b=normalizeGenetics(p2?.genetics).loci[l].alleles;if(!known(a)||!known(b))return null;results[l]=crossLocus(l,a,b).outcomes;}let rows=[{genotype:{},probability:1}];Object.keys(RABBIT_LOCI).forEach(l=>{const n=[];rows.forEach(r=>results[l].forEach(o=>n.push({genotype:{...r.genotype,[l]:o.alleles},probability:r.probability*o.probability})));rows=n;});const map=new Map();rows.forEach(r=>{const ph=phenotypeFromGenotype(r.genotype),k=`${ph.name}|${ph.scope}`,e=map.get(k)||{name:ph.name,family:ph.family,scope:ph.scope,probability:0,genotypes:[]};e.probability+=r.probability;e.genotypes.push(r);map.set(k,e);});return[...map.values()].sort((a,b)=>b.probability-a.probability||a.name.localeCompare(b.name));}
function offspringPairs(l,a,b){const m=new Map();a.forEach(x=>b.forEach(y=>new Set(x).forEach(i=>new Set(y).forEach(j=>{const p=sortPair(l,[i,j]);m.set(pairKey(l,p),p);})))) ;return[...m.values()];}
function possiblePhenotypes(p1,p2,limit=12000){const lp={};Object.keys(RABBIT_LOCI).forEach(l=>lp[l]=offspringPairs(l,possiblePairsForLocus(p1,p1?.color||p1?.variety,l),possiblePairsForLocus(p2,p2?.color||p2?.variety,l)));let rows=[{genotype:{}}];for(const l of Object.keys(RABBIT_LOCI)){const n=[];for(const r of rows){for(const p of lp[l]){n.push({genotype:{...r.genotype,[l]:p}});if(n.length>=limit)break;}if(n.length>=limit)break;}rows=n;}const m=new Map();rows.forEach(r=>{const ph=phenotypeFromGenotype(r.genotype);if(ph.name!=='Unknown')m.set(`${ph.name}|${ph.scope}`,ph);});return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name));}
const genotypeText=g=>{const n=normalizeGenetics(g);return Object.keys(RABBIT_LOCI).map(l=>`${l}:${n.loci[l].alleles.join('')}`).join(' ');};
function ancestorMap(animal,animals,max=3){const by=new Map((animals||[]).map(a=>[String(a.id),a])),out=new Map();function walk(cur,d){if(!cur||d>max)return;[cur.sireId,cur.damId].filter(Boolean).forEach(id=>{const a=by.get(String(id));if(!a)return;const k=String(a.id),prev=out.get(k);if(!prev||d<prev.depth)out.set(k,{animal:a,depth:d});walk(a,d+1);});}walk(animal,1);return out;}
function sharedAncestors(a,b,animals,max=3){const x=ancestorMap(a,animals,max),y=ancestorMap(b,animals,max),o=[];x.forEach((v,id)=>{const w=y.get(id);if(w)o.push({id,name:v.animal.name||v.animal.tag||id,parent1Depth:v.depth,parent2Depth:w.depth});});return o.sort((m,n)=>(m.parent1Depth+m.parent2Depth)-(n.parent1Depth+n.parent2Depth));}
const RECESSIVE={A:{allele:'a',colors:['black','blue','chocolate','lilac','black tort','blue tort','chocolate tort','lilac tort']},B:{allele:'b',colors:['chocolate','lilac','chocolate agouti','lynx','chocolate otter','lilac otter','chocolate tort','lilac tort']},C:{allele:'c',colors:['rew','red eyed white','red-eyed white']},D:{allele:'d',colors:['blue','lilac','opal','lynx','blue otter','lilac otter','blue tort','lilac tort']},E:{allele:'e',colors:['black tort','blue tort','chocolate tort','lilac tort']}};
const proof=(color,l)=>RECESSIVE[l]?.colors.includes(normColor(color))?RECESSIVE[l].allele:null;
function pedigreeEvidence(animal,animals,max=3){const by=new Map((animals||[]).map(a=>[String(a.id),a])),o=[];function walk(id,d,rel){if(!id||d>max)return;const a=by.get(String(id));if(!a)return;Object.keys(RECESSIVE).forEach(l=>{const al=proof(a.color||a.variety,l);if(al)o.push({locus:l,allele:al,status:d===1?'confirmed':'possible',source:'pedigree',relatedAnimalId:a.id,note:d===1?`${animal.name||'This rabbit'} must inherit ${al} at the ${l} locus from ${a.name||rel}, whose recorded phenotype requires ${al}${al}.`:`${al} appears in the pedigree through ${a.name||rel}; inheritance to ${animal.name||'this rabbit'} is possible but not established.`,depth:d});});walk(a.sireId,d+1,'sire');walk(a.damId,d+1,'dam');}walk(animal?.sireId,1,'sire');walk(animal?.damId,1,'dam');return o;}
function offspringEvidenceForParent(parent,mate,offspring){const o=[];(offspring||[]).forEach(c=>Object.keys(RECESSIVE).forEach(l=>{const a=proof(c.color||c.variety,l);if(a)o.push({locus:l,allele:a,status:'inferred',source:'offspring',relatedAnimalId:c.id,mateId:mate?.id||null,note:`${parent?.name||'Parent'} supplied ${a} at the ${l} locus to ${c.name||'recorded offspring'}, whose recorded phenotype requires ${a}${a}.`});}));const m=new Map();o.forEach(e=>m.set(`${e.locus}|${e.allele}|${e.relatedAnimalId}`,e));return[...m.values()];}
function applyEvidenceToGenetics(g,items){const out=normalizeGenetics(g),conf=out.conflicts.slice();(items||[]).forEach(e=>{if(!RABBIT_LOCI[e.locus]||!e.allele)return;const r=out.loci[e.locus],p=r.alleles.slice(),has=p.includes(e.allele),cp=PRIORITY[r.status]||0,ip=PRIORITY[e.status]||0;if(!has&&known(p)&&cp>=3)conf.push({locus:e.locus,existing:p.slice(),incomingAllele:e.allele,evidence:e,createdAt:new Date().toISOString()});else if(!has){const i=p.indexOf('_');if(i>=0)p[i]=e.allele;else if(!known(p)||ip>cp)p[1]=e.allele;r.alleles=sortPair(e.locus,p);}if(ip>cp)r.status=e.status;if(e.note)r.note=e.note;r.source=e.source||r.source;out.evidence.push({createdAt:new Date().toISOString(),...e});});out.conflicts=conf;out.updatedAt=new Date().toISOString();return out;}
function previousOffspring(p1,p2,animals,births){const ids=new Set([String(p1?.id||''),String(p2?.id||'')]),birthIds=new Set((births||[]).filter(b=>{const x=new Set([String(b.sireId||''),String(b.damId||'')]);return x.size===ids.size&&[...ids].every(id=>x.has(id));}).map(b=>String(b.id)));return(animals||[]).filter(a=>(ids.has(String(a.sireId||''))&&ids.has(String(a.damId||'')))||birthIds.has(String(a.sourceBirthId||'')));}
function performanceForAnimal(animal,breedings,births){const id=String(animal?.id||''),att=(breedings||[]).filter(b=>String(b.femaleId||b.damId||'')===id||String(b.maleId||b.sireId||'')===id),del=att.filter(b=>/delivered|completed/i.test(String(b.status||''))).length,rb=(births||[]).filter(b=>String(b.damId||'')===id||String(b.sireId||'')===id),sum=k=>rb.reduce((t,b)=>t+(Number(b[k])||0),0),alive=sum('bornAlive'),weaned=sum('weaned');return{breedings:att.length,successfulBreedings:del,births:rb.length,bornAlive:alive,stillborn:sum('stillborn'),weaned,survivalRate:alive?weaned/alive:null,averageLitterSize:rb.length?alive/rb.length:null};}
const deepClone=v=>JSON.parse(JSON.stringify(v));
function createPredictionSnapshot(analysis,metadata){const now=new Date().toISOString();return Object.freeze({id:`genetics_prediction_${now.replace(/[^0-9]/g,'')}_${Math.random().toString(36).slice(2,8)}`,version:1,engineVersion:VERSION,createdAt:now,metadata:deepClone(metadata||{}),analysis:deepClone(analysis)});}
function analyzePairing(p1,p2,ctx={}){if(canonicalSpecies(p1?.species)!=='Rabbit'||canonicalSpecies(p2?.species)!=='Rabbit')return{supported:false,reason:'Rabbit coat-color genetics is the first production genetics module in Alpha v1.5.1.'};const exact=exactCross(p1,p2),possible=exact?[]:possiblePhenotypes(p1,p2),animals=ctx.animals||[],births=ctx.births||[],kids=previousOffspring(p1,p2,animals,births),colors=new Map();kids.forEach(c=>{const x=clean(c.color||c.variety)||'Unrecorded';colors.set(x,(colors.get(x)||0)+1);});const incomplete=[];[p1,p2].forEach(p=>{const g=normalizeGenetics(p.genetics);Object.keys(RABBIT_LOCI).forEach(l=>{if(!known(g.loci[l].alleles))incomplete.push({animalId:p.id,animalName:p.name,locus:l,alleles:g.loci[l].alleles.slice()});});});return{supported:true,engineVersion:VERSION,species:'Rabbit',parent1:{id:p1.id,name:p1.name,color:p1.color||p1.variety||'',genotype:genotypeText(p1.genetics)},parent2:{id:p2.id,name:p2.name,color:p2.color||p2.variety||'',genotype:genotypeText(p2.genetics)},exact:Boolean(exact),exactOutcomes:exact||[],possibleOutcomes:possible,incompleteLoci:incomplete,sharedAncestors:sharedAncestors(p1,p2,animals,3),pedigreeEvidence:{parent1:pedigreeEvidence(p1,animals,3),parent2:pedigreeEvidence(p2,animals,3)},previousOffspring:[...colors].map(([color,count])=>({color,count})),explanation:exact?'Both parents have complete supported A/B/C/D/E genotypes, so displayed percentages are Mendelian probabilities for those loci. Modifier genes can still affect the visible variety.':'One or more parental alleles are unknown. HerdHarbor therefore shows genetically possible core color families without pretending missing carrier information is known.',disclaimer:'Predictions use recorded A/B/C/D/E genetics and supported phenotype mappings. Rabbit coat color can involve additional modifier genes, breed-specific expression, incomplete records, and misidentified phenotypes; actual offspring may differ.'};}
const RabbitGeneticsModule=registerSpeciesModule('Rabbit',{version:1,name:'Rabbit coat-color genetics',loci:RABBIT_LOCI,analyzePairing,phenotypeFromGenotype,pedigreeEvidence,offspringEvidenceForParent,sources:[{title:'Oregon State University Extension — Rabbit coat color genetics summary table',url:'https://extension.oregonstate.edu/catalog/em-9708-rabbit-coat-color-genetics-summary-table'},{title:'Oregon State University Extension — Understanding rabbit coat-color genes',url:'https://extension.oregonstate.edu/catalog/understanding-genetics-behind-rabbit-coat-colors-part-2-coat-color-genes'},{title:'Utah State University Extension — Rabbit Breeding and Management',url:'https://extension.usu.edu/small-acreage-livestock/research/rabbit-breeding-and-management-a-guide-for-producers'}]});
return Object.freeze({VERSION,EVIDENCE_STATUS,RABBIT_LOCI,RabbitGeneticsModule,canonicalSpecies,speciesTerms,registerSpeciesModule,getSpeciesModule,normalizeGenetics,colorConstraints,patternLabelForColor,possiblePairsForLocus,crossLocus,phenotypeFromGenotype,exactCross,possiblePhenotypes,pedigreeEvidence,offspringEvidenceForParent,applyEvidenceToGenetics,sharedAncestors,previousOffspring,performanceForAnimal,createPredictionSnapshot,analyzePairing,genotypeText,deepClone});
});
