(() => {
"use strict";
const B=window.HerdHarborBreedingIntelligenceCore;if(!B)return;
const V="1.6.1",L="hh-rabbit-colors-v161",R=B.RABBIT_LOCI;
const s=v=>String(v==null?"":v).trim(),h=v=>s(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");
const sex=v=>{v=s(v).toLowerCase().replace(/[()]/g," ").replace(/\s+/g," ").trim();return ["male","buck","m","male buck","buck male"].includes(v)?"male":["female","doe","f","female doe","doe female"].includes(v)?"female":"unknown"};
const active=a=>B.canonicalSpecies(a?.species)==="Rabbit"&&(!s(a.status)||["active","breeding"].includes(s(a.status).toLowerCase()));
const C=["Black","Blue","Chocolate","Lilac","Chestnut","Chestnut Agouti","Opal","Chocolate Agouti","Lynx","Black Otter","Blue Otter","Chocolate Otter","Lilac Otter","Black Tort","Blue Tort","Chocolate Tort","Lilac Tort","Orange","Red","Fawn","Cream","Black Harlequin","Blue Harlequin","Chocolate Harlequin","Lilac Harlequin","Black Magpie","Blue Magpie","Chocolate Magpie","Lilac Magpie","Tricolor","Chinchilla","Squirrel","Chocolate Chinchilla","Lilac Chinchilla","Black Silver Marten","Blue Silver Marten","Chocolate Silver Marten","Lilac Silver Marten","Black Pointed White","Blue Pointed White","Chocolate Pointed White","Lilac Pointed White","Pointed White","Himalayan","Californian","Red Eyed White (REW)","Blue Eyed White (BEW)","Black Steel","Blue Steel","Chocolate Steel","Lilac Steel","Sable Point","Smoke Pearl Point","Siamese Sable","Siamese Smoke Pearl","Frosty","Blue Frosty"];
const broken=["Black","Blue","Chocolate","Lilac","Chestnut","Opal","Black Otter","Blue Otter","Black Tort","Blue Tort","Orange","Fawn","Black Harlequin","Blue Harlequin","Chocolate Harlequin","Lilac Harlequin","Black Magpie","Blue Magpie","Chocolate Magpie","Lilac Magpie"].map(x=>`Broken ${x}`),COL=[...C,...broken];
function isBew(v){const n=s(v).toLowerCase().replace(/[()]/g," ").replace(/\s+/g," ").trim();return /\bblue[- ]eyed white\b/.test(n)||/\bbew\b/.test(n)}
function color(v){return s(v).toLowerCase().replace(/^(broken|booted|charlie|solid)\s+/,"").replace(/\s+(vm|vc|vienna marked|vienna carrier)$/ ,"").replace(/^vienna marked\s+/,"").replace(/\(rew\)/g,"").trim()}
function pigmentRule(n){return{B:/chocolate|lilac/.test(n)?[["b","b"]]:[["B","_"]],D:/blue|lilac|opal|lynx|squirrel|smoke pearl|cream|fawn/.test(n)?[["d","d"]]:[["D","_"]]}}
function rule(v){const n=color(v);if(!n)return null;if(["rew","red eyed white","red-eyed white","ruby eyed white","ruby-eyed white"].includes(n))return{C:[["c","c"]]};let q=pigmentRule(n);if(/magpie/.test(n))return{...q,A:[["A","_"]],C:[["cchd","_"]],E:[["ej","ej"],["ej","e"]]};if(/harlequin|tricolor|tri color|tri-color/.test(n))return{...q,A:[["A","_"]],C:[["C","_"]],E:[["ej","ej"],["ej","e"]]};if(/silver marten/.test(n))return{...q,A:[["at","_"]],C:[["cchd","_"]],E:[["E","_"]]};if(/chinchilla|squirrel/.test(n))return{...q,A:[["A","_"]],C:[["cchd","_"]],E:[["E","_"]]};if(/frosty/.test(n))return{...q,A:[["A","_"]],C:[["cchd","_"]],E:[["e","e"]]};if(/pointed white|himalayan|californian/.test(n))return{...q,C:[["ch","ch"],["ch","c"]]};if(/sable point|smoke pearl point/.test(n))return{...q,A:[["a","a"]],C:[["cchl","_"]],E:[["e","e"]]};if(/siamese sable|siamese smoke pearl|^smoke pearl$/.test(n))return{...q,A:[["a","a"]],C:[["cchl","_"]],E:[["E","_"]]};if(/steel/.test(n))return{...q,A:[["A","_"]],C:[["C","_"]],E:[["Es","_"]]};if(/tort/.test(n))return{...q,A:[["a","a"]],C:[["C","_"]],E:[["e","e"]]};if(/orange|red|fawn|cream/.test(n))return{...q,A:[["A","_"]],C:[["C","_"]],E:[["e","e"]]};if(/otter/.test(n))return{...q,A:[["at","_"]],C:[["C","_"]],E:[["E","_"]]};if(/chestnut|agouti|opal|lynx/.test(n))return{...q,A:[["A","_"]],C:[["C","_"]],E:[["E","_"]]};if(/^(black|blue|chocolate|lilac)$/.test(n))return{...q,A:[["a","a"]],C:[["C","_"]],E:[["E","_"]]};return null}
function mapV2(a,b,ctx){const x=B.analyzePairing(a,b,ctx||{}),out=[];if(!x?.supported)return{inputs:[s(a.color||a.variety),s(b.color||b.variety)],bad:[],warning:x?.reason||"Unsupported pairing",out:[]};if(x.exact)(x.exactOutcomes||[]).forEach(o=>out.push({name:o.name,family:o.family,badge:`${(o.probability*100).toFixed((o.probability*100)%1?1:0)}%`}));else if(x.exactBase)(x.baseOutcomes||[]).forEach(o=>out.push({name:o.name,family:`${o.family} · base color`,badge:`${(o.probability*100).toFixed((o.probability*100)%1?1:0)}%`}));else(x.conditionalOutcomes||[]).forEach(o=>out.push({name:o.name,family:o.requires||"Conditional genetics",badge:`${Math.round(o.minProbability*100)}–${Math.round(o.maxProbability*100)}%`}));return{inputs:[s(a.color||a.variety),s(b.color||b.variety)],bad:[],warning:"",out,note:x.explanation||""};}
const rk=(l,a)=>{let i=R[l]?.dominance?.indexOf(a);return i<0?999:i},sort=(l,p)=>{p=(p||["_","_"]).slice(0,2);while(p.length<2)p.push("_");return p.sort((a,b)=>a==="_"?1:b==="_"?-1:rk(l,a)-rk(l,b))},known=p=>p.length===2&&p.every(x=>x&&x!=="_");
function all(l){let a=R[l]?.dominance||[],o=[];for(let i=0;i<a.length;i++)for(let j=i;j<a.length;j++)o.push([a[i],a[j]]);return o}function match(l,pat){return all(l).filter(p=>{let z=sort(l,p);return [[z[0],z[1]],[z[1],z[0]]].some(x=>pat.every((t,i)=>t==="_"||t===x[i]))})}
function pairs(a,l){let x=B.normalizeGenetics(a?.genetics).loci[l]?.alleles||["_","_"],p=all(l);if(x.some(v=>v&&v!=="_"))p=match(l,x);let q=rule(a.color||a.variety);if(q?.[l]){let ok=new Set;q[l].forEach(t=>match(l,t).forEach(v=>ok.add(sort(l,v).join("/"))));p=p.filter(v=>ok.has(sort(l,v).join("/")))}return p}
function childPairs(l,a,b){let m=new Map;a.forEach(x=>b.forEach(y=>new Set(x).forEach(i=>new Set(y).forEach(j=>{let p=sort(l,[i,j]);m.set(p.join("/"),p)}))));return[...m.values()]}
function dom(l,p){return p.filter(x=>x&&x!=="_").sort((a,b)=>rk(l,a)-rk(l,b))[0]||"_"}function ph(g){let A=sort("A",g.A),Bb=sort("B",g.B),Cc=sort("C",g.C),D=sort("D",g.D),E=sort("E",g.E);if(![A,Bb,Cc,D,E].every(known))return null;if(Cc[0]==="c"&&Cc[1]==="c")return["REW","Red-eyed white"];let choc=Bb[0]==="b"&&Bb[1]==="b",dil=D[0]==="d"&&D[1]==="d",p=choc&&dil?"Lilac":choc?"Chocolate":dil?"Blue":"Black",c=dom("C",Cc),e=dom("E",E),aa=dom("A",A);if(c==="ch")return[`${p} Pointed White`,"Pointed White"];if(e==="ej")return[c==="cchd"?`${p} Magpie`:`${p} Harlequin`,c==="cchd"?"Magpie":"Harlequin"];if(c==="cchd")return aa==="at"?[`${p} Silver Marten`,"Silver Marten"]:aa==="A"?[({Black:"Chinchilla",Blue:"Squirrel",Chocolate:"Chocolate Chinchilla",Lilac:"Lilac Chinchilla"})[p],"Chinchilla"]:[p,"Self"];if(Cc[0]==="cchl")return E[0]==="e"&&E[1]==="e"?[(p==="Blue"||p==="Lilac")?"Smoke Pearl Point":"Sable Point","Shaded Point"]:[(p==="Blue"||p==="Lilac")?"Siamese Smoke Pearl":"Siamese Sable","Shaded"];if(E[0]==="e"&&E[1]==="e")return aa==="a"?[`${p} Tort`,"Tortoiseshell"]:aa==="A"?[(p==="Blue"||p==="Lilac")?"Fawn/Cream family":"Orange/Red family","Non-extension agouti"]:["Non-extension tan-pattern family","Non-extension"];if(e==="Es"&&aa==="A")return[`${p} Steel`,"Steel"];if(aa==="A")return[({Black:"Chestnut Agouti",Blue:"Opal",Chocolate:"Chocolate Agouti",Lilac:"Lynx"})[p],"Agouti"];if(aa==="at")return[`${p} Otter`,"Tan pattern"];return[p,"Self"]}
function legacyAnalyze(a,b){let inputs=[s(a.color||a.variety),s(b.color||b.variety)],bad=[];[a,b].forEach((x,i)=>{let g=B.normalizeGenetics(x.genetics),has=Object.values(g.loci||{}).some(y=>y?.alleles?.some(z=>z&&z!=="_"));if(inputs[i]&&!rule(inputs[i])&&!has)bad.push({name:x.name||(!i?"Buck":"Doe"),color:inputs[i]})});if(bad.length)return{inputs,bad,out:[],warning:""};let by={};for(let l of ["A","B","C","D","E"])by[l]=childPairs(l,pairs(a,l),pairs(b,l));let rows=[{}];for(let l of ["A","B","C","D","E"]){let n=[];for(let x of rows){for(let p of by[l]){n.push({...x,[l]:p});if(n.length>=16000)break}if(n.length>=16000)break}rows=n}let m=new Map;rows.forEach(g=>{let x=ph(g);if(x)m.set(x[0],{name:x[0],family:x[1]})});return{inputs,bad:[],warning:"",out:[...m.values()].sort((x,y)=>x.name.localeCompare(y.name)),note:"Compatibility result only; HerdHarbor Genetics v2 is the user-facing deterministic predictor."}}
function analyze(a,b,ctx={}){const inputs=[s(a.color||a.variety),s(b.color||b.variety)],bew=inputs.map(isBew);if(bew[0]&&bew[1])return{inputs,bad:[],warning:"",note:"Every kit receives one recessive Vienna allele from each parent, so the Vienna locus is 100% vv.",out:[{name:"Blue Eyed White (BEW)",family:"Vienna locus · vv × vv → 100% vv",badge:"100% vv"}]};if(bew[0]||bew[1]){const mate=bew[0]?b:a,g=B.normalizeGenetics(mate?.genetics),v=g?.loci?.V?.alleles||[],status=s(mate?.viennaStatus||g?.vienna?.status);if(!(v.some(x=>x&&x!=="_")||status&&!/unknown/i.test(status)))return{inputs,bad:[],out:[],warning:"BEW is controlled by the Vienna locus. HerdHarbor needs the other rabbit's Vienna status before it can calculate a reliable BEW percentage."};}return Array.isArray(B.DISPLAY_LOCI)?mapV2(a,b,ctx):legacyAnalyze(a,b)}
function colors(){let a=COL.slice().sort(),d=document.getElementById(L);if(!d){const target=document.body||document.documentElement||document.head;if(!target)return;d=document.createElement("datalist");d.id=L;target.appendChild(d)}const markup=a.map(c=>`<option value="${h(c)}"></option>`).join("");if(d.innerHTML!==markup)d.innerHTML=markup;document.querySelectorAll('input[name="color"]').forEach(i=>i.setAttribute("list",L))}
// Pair Analysis remains additive and does not intercept unrelated form events.
// Ancestor colors: NOT used as direct prediction inputs; deterministic pedigree evidence is handled by the v2 engine.
document.addEventListener("focusin",e=>{if(e.target?.matches?.('input[name="color"]'))colors()});
function boot(){colors();window.HerdHarborBreedingPairHotfix=Object.freeze({version:V,canonicalSex:sex,isPairingRabbit:active,standardColors:COL.slice(),analyze,openPairAnalysis:()=>window.HerdHarborRabbitGeneticsV2?.openPrediction?.()})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot,{once:true}):boot();
})();
