(() => {
"use strict";
const B=window.HerdHarborBreedingIntelligenceCore;if(!B)return;
const V="1.4.1",K="herdharbor_pre_alpha_v1",L="hh-rabbit-colors-v141",R=B.RABBIT_LOCI;let modal=null;
const s=v=>String(v==null?"":v).trim(),h=v=>s(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const sex=v=>{v=s(v).toLowerCase().replace(/[()]/g," ").replace(/\s+/g," ").trim();return ["male","buck","m","male buck","buck male"].includes(v)?"male":["female","doe","f","female doe","doe female"].includes(v)?"female":"unknown"};
const active=a=>B.canonicalSpecies(a?.species)==="Rabbit"&&(!s(a.status)||["active","breeding"].includes(s(a.status).toLowerCase()));
const C=["Black","Blue","Chocolate","Lilac","Chestnut","Chestnut Agouti","Opal","Chocolate Agouti","Lynx","Black Otter","Blue Otter","Chocolate Otter","Lilac Otter","Black Tort","Blue Tort","Chocolate Tort","Lilac Tort","Orange","Red","Fawn","Cream","Black Harlequin","Blue Harlequin","Chocolate Harlequin","Lilac Harlequin","Black Magpie","Blue Magpie","Chocolate Magpie","Lilac Magpie","Tricolor","Chinchilla","Squirrel","Chocolate Chinchilla","Lilac Chinchilla","Black Silver Marten","Blue Silver Marten","Chocolate Silver Marten","Lilac Silver Marten","Black Pointed White","Blue Pointed White","Chocolate Pointed White","Lilac Pointed White","Pointed White","Himalayan","Californian","Red Eyed White (REW)","Black Steel","Blue Steel","Chocolate Steel","Lilac Steel","Sable Point","Smoke Pearl Point","Siamese Sable","Siamese Smoke Pearl","Frosty","Blue Frosty"];
const broken=["Black","Blue","Chocolate","Lilac","Chestnut","Opal","Black Otter","Blue Otter","Black Tort","Blue Tort","Orange","Fawn","Black Harlequin","Blue Harlequin","Chocolate Harlequin","Lilac Harlequin","Black Magpie","Blue Magpie","Chocolate Magpie","Lilac Magpie"].map(x=>`Broken ${x}`),COL=[...C,...broken];
function color(v){return s(v).toLowerCase().replace(/^(broken|booted|charlie|solid)\s+/,"").replace(/\s+(vm|vc|vienna marked|vienna carrier)$/ ,"").replace(/^vienna marked\s+/,"").replace(/\(rew\)/g,"").trim()}
function pigmentRule(n){let Bp=/chocolate|lilac/.test(n)?[["b","b"]]:[["B","_"]],Dp=/blue|lilac|opal|lynx|squirrel|smoke pearl|cream|fawn/.test(n)?[["d","d"]]:[["D","_"]];return{B:Bp,D:Dp}}
function rule(v){const n=color(v);if(!n)return null;if(["rew","red eyed white","red-eyed white","ruby eyed white","ruby-eyed white"].includes(n))return{C:[["c","c"]]};let q=pigmentRule(n);
 if(/magpie/.test(n))return{...q,A:[["A","_"]],C:[["cchd","_"]],E:[["ej","ej"],["ej","e"]]};
 if(/harlequin|tricolor|tri color|tri-color/.test(n))return{...q,A:[["A","_"]],C:[["C","_"]],E:[["ej","ej"],["ej","e"]]};
 if(/silver marten/.test(n))return{...q,A:[["at","_"]],C:[["cchd","_"]],E:[["E","_"]]};
 if(/chinchilla|squirrel/.test(n))return{...q,A:[["A","_"]],C:[["cchd","_"]],E:[["E","_"]]};
 if(/frosty/.test(n))return{...q,A:[["A","_"]],C:[["cchd","_"]],E:[["e","e"]]};
 if(/pointed white|himalayan|californian/.test(n))return{...q,C:[["ch","ch"],["ch","c"]]};
 if(/sable point|smoke pearl point/.test(n))return{...q,A:[["a","a"]],C:[["cchl","_"]],E:[["e","e"]]};
 if(/siamese sable|siamese smoke pearl|^smoke pearl$/.test(n))return{...q,A:[["a","a"]],C:[["cchl","_"]],E:[["E","_"]]};
 if(/steel/.test(n))return{...q,A:[["A","_"]],C:[["C","_"]],E:[["Es","_"]]};
 if(/tort/.test(n))return{...q,A:[["a","a"]],C:[["C","_"]],E:[["e","e"]]};
 if(/orange|red|fawn|cream/.test(n))return{...q,A:[["A","_"]],C:[["C","_"]],E:[["e","e"]]};
 if(/otter/.test(n))return{...q,A:[["at","_"]],C:[["C","_"]],E:[["E","_"]]};
 if(/chestnut|agouti|opal|lynx/.test(n))return{...q,A:[["A","_"]],C:[["C","_"]],E:[["E","_"]]};
 if(/^(black|blue|chocolate|lilac)$/.test(n))return{...q,A:[["a","a"]],C:[["C","_"]],E:[["Ed","_"],["Es","_"],["E","_"]]};return null}
const rk=(l,a)=>{let i=R[l].dominance.indexOf(a);return i<0?999:i},sort=(l,p)=>{p=(p||["_","_"]).slice(0,2);while(p.length<2)p.push("_");return p.sort((a,b)=>a==="_"?1:b==="_"?-1:rk(l,a)-rk(l,b))},known=p=>p.length===2&&p.every(x=>x&&x!=="_");
function all(l){let a=R[l].dominance,o=[];for(let i=0;i<a.length;i++)for(let j=i;j<a.length;j++)o.push([a[i],a[j]]);return o}function match(l,pat){return all(l).filter(p=>{let z=sort(l,p);return [[z[0],z[1]],[z[1],z[0]]].some(x=>pat.every((t,i)=>t==="_"||t===x[i]))})}
function direct(a,l){let x=B.normalizeGenetics(a?.genetics).loci[l];return s(x.source).toLowerCase()==="pedigree"?{...x,alleles:["_","_"]}:x}
function pairs(a,l){let x=direct(a,l).alleles,p=all(l);if(x.some(v=>v&&v!=="_"))p=match(l,x);let q=rule(a.color||a.variety);if(q?.[l]){let ok=new Set;q[l].forEach(t=>match(l,t).forEach(v=>ok.add(sort(l,v).join("/"))));p=p.filter(v=>ok.has(sort(l,v).join("/")))}return p}
function childPairs(l,a,b){let m=new Map;a.forEach(x=>b.forEach(y=>new Set(x).forEach(i=>new Set(y).forEach(j=>{let p=sort(l,[i,j]);m.set(p.join("/"),p)}))));return[...m.values()]}
function dom(l,p){return p.filter(x=>x&&x!=="_").sort((a,b)=>rk(l,a)-rk(l,b))[0]||"_"}function ph(g){let A=sort("A",g.A),Bb=sort("B",g.B),Cc=sort("C",g.C),D=sort("D",g.D),E=sort("E",g.E);if(![A,Bb,Cc,D,E].every(known))return null;if(Cc[0]==="c"&&Cc[1]==="c")return["REW","Red-eyed white"];let choc=Bb[0]==="b"&&Bb[1]==="b",dil=D[0]==="d"&&D[1]==="d",p=choc&&dil?"Lilac":choc?"Chocolate":dil?"Blue":"Black",c=dom("C",Cc),e=dom("E",E),a=dom("A",A);if(c==="ch")return[`${p} Pointed White`,"Pointed White"];if(e==="ej")return[c==="cchd"?`${p} Magpie`:`${p} Harlequin`,c==="cchd"?"Magpie":"Harlequin"];if(c==="cchd")return[a==="at"?[`${p} Silver Marten`,"Silver Marten"]:a==="A"?[({Black:"Chinchilla",Blue:"Squirrel",Chocolate:"Chocolate Chinchilla",Lilac:"Lilac Chinchilla"})[p],"Chinchilla"]:[p,"Self"]][0];if(c==="cchl")return E[0]==="e"&&E[1]==="e"?[(p==="Blue"||p==="Lilac")?"Smoke Pearl Point":"Sable Point","Shaded Point"]:[(p==="Blue"||p==="Lilac")?"Siamese Smoke Pearl":"Siamese Sable","Shaded"];if(E[0]==="e"&&E[1]==="e")return a==="a"?[`${p} Tort`,"Tortoiseshell"]:a==="A"?[(p==="Blue"||p==="Lilac")?"Fawn/Cream family":"Orange/Red family","Non-extension agouti"]:["Non-extension tan-pattern family","Non-extension"];if(e==="Es"&&a==="A")return[`${p} Steel`,"Steel"];if(a==="A")return[({Black:"Chestnut Agouti",Blue:"Opal",Chocolate:"Chocolate Agouti",Lilac:"Lynx"})[p],"Agouti"];if(a==="at")return[`${p} Otter`,"Tan pattern"];return[p,"Self"]}
function analyze(a,b){let inputs=[s(a.color||a.variety),s(b.color||b.variety)],bad=[];[a,b].forEach((x,i)=>{let g=B.normalizeGenetics(x.genetics),has=Object.values(g.loci).some(y=>s(y.source).toLowerCase()!=="pedigree"&&y.alleles.some(z=>z&&z!=="_"));if(inputs[i]&&!rule(inputs[i])&&!has)bad.push({name:x.name||(!i?"Buck":"Doe"),color:inputs[i]})});if(bad.length)return{inputs,bad,out:[]};let by={};for(let l of Object.keys(R))by[l]=childPairs(l,pairs(a,l),pairs(b,l));let rows=[{}];for(let l of Object.keys(R)){let n=[];for(let x of rows){for(let p of by[l]){n.push({...x,[l]:p});if(n.length>=16000)break}if(n.length>=16000)break}rows=n}let m=new Map;rows.forEach(g=>{let x=ph(g);if(x)m.set(x[0],{name:x[0],family:x[1]})});return{inputs,bad:[],out:[...m.values()].sort((x,y)=>x.name.localeCompare(y.name))}}
function state(){try{let x=JSON.parse(localStorage.getItem(K)||"{}");x.animals=Array.isArray(x.animals)?x.animals:[];return x}catch{return{animals:[]}}}const label=a=>{let n=a.name||a.tag||a.id||"Unnamed rabbit",c=a.color||a.variety;return c?`${n} — ${c}`:n},opts=(a,id)=>'<option value="">Select a rabbit…</option>'+a.map(x=>`<option value="${h(x.id)}" ${String(x.id)===String(id||"")?"selected":""}>${h(label(x))}</option>`).join("");
function close(){modal?.remove();modal=null}function open(bid="",did="",run=false){let a=state().animals.filter(active),bucks=a.filter(x=>sex(x.sex)==="male"),does=a.filter(x=>sex(x.sex)==="female"),buck=bucks.find(x=>String(x.id)===String(bid)),doe=does.find(x=>String(x.id)===String(did)),body=`<div class="hh-bi-pair-selectors"><label>Buck<select id="v141-buck">${opts(bucks,buck?.id)}</select></label><label>Doe<select id="v141-doe">${opts(does,doe?.id)}</select></label><button type="button" class="primary" id="v141-run">Analyze pairing</button></div><p class="hh-bi-note">Only current Active/Breeding rabbits appear here. Ancestor Only and inactive records are excluded.</p>`;if(run&&buck&&doe){let r=analyze(buck,doe);body+=`<div class="hh-bi-profile-summary"><strong>Prediction inputs</strong><span>Buck: ${h(r.inputs[0]||"Not recorded")}</span><span>Doe: ${h(r.inputs[1]||"Not recorded")}</span><span>Ancestor colors: NOT used</span></div>`;body+=r.bad.length?`<div class="hh-bi-warning"><strong>Color mapping needed.</strong> ${r.bad.map(x=>`${h(x.name)}: ${h(x.color)}`).join("; ")}. Choose a listed color or enter direct genetics.</div>`:`<div class="hh-bi-results">${r.out.map(x=>`<div class="hh-bi-result-row"><div><strong>${h(x.name)}</strong><span>${h(x.family)}</span></div><b>Possible</b></div>`).join("")||"<p>No supported outcome calculated.</p>"}</div><p class="hh-bi-note">Possible colors use only the selected rabbits’ recorded colors and direct A/B/C/D/E genetics. Pedigree and ancestor colors do not alter this list.</p>`}else if(run)body+='<div class="hh-bi-warning">Choose one buck and one doe.</div>';else body+='<div class="hh-bi-empty">Choose a buck and doe, then run Pair Analysis.</div>';close();modal=document.createElement("div");modal.className="hh-bi-modal-backdrop";modal.innerHTML=`<section class="hh-bi-modal"><header><div><span class="hh-bi-kicker">HerdHarbor Breeding Intelligence · Hotfix ${V}</span><h2>Breeding Pair Analysis</h2></div><button class="hh-bi-close" data-v141-close>×</button></header><div class="hh-bi-modal-body">${body}</div></section>`;document.body.appendChild(modal);modal.querySelector("#v141-run")?.addEventListener("click",()=>open(modal.querySelector("#v141-buck").value,modal.querySelector("#v141-doe").value,true))}
function colors(){let x=state().animals.filter(a=>B.canonicalSpecies(a.species)==="Rabbit").map(a=>s(a.color||a.variety)).filter(Boolean),a=[...new Set([...COL,...x])].sort();let d=document.getElementById(L);if(!d){d=document.createElement("datalist");d.id=L;document.body.appendChild(d)}d.innerHTML=a.map(c=>`<option value="${h(c)}"></option>`).join("");document.querySelectorAll('input[name="color"]').forEach(i=>{let f=i.closest("form"),sp=f?.querySelector('[name="species"]'),apply=()=>{if(B.canonicalSpecies(sp?.value||"Rabbit")==="Rabbit")i.setAttribute("list",L);else if(i.getAttribute("list")===L)i.removeAttribute("list")};apply();if(sp&&!sp.dataset.v141){sp.dataset.v141="1";sp.addEventListener("change",apply)}})}
document.addEventListener("click",e=>{if(e.target.closest('[data-bi-action="pair"]')){e.preventDefault();e.stopImmediatePropagation();open()}else if(e.target.closest("[data-v141-close]")||e.target===modal)close()},true);document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});let ob=new MutationObserver(()=>colors());function boot(){colors();ob.observe(document.body,{childList:true,subtree:true});window.HerdHarborBreedingPairHotfix=Object.freeze({version:V,canonicalSex:sex,isPairingRabbit:active,standardColors:COL.slice(),analyze,openPairAnalysis:open})}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot,{once:true}):boot();
})();