(function(root){
  "use strict";
  if(!root?.document)return;
  let Core=root.HerdHarborGeneticsV2Phase1Core,observer=null,uiQueued=false,propagationTimer=null,propagationRunning=false,retryCount=0;
  const clean=value=>String(value==null?"":value).trim(),lower=value=>clean(value).toLowerCase();
  const esc=value=>String(value==null?"":value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
  const pct=value=>`${Math.round(Number(value||0)*100)}%`;
  function stateNow(){try{return root.HerdHarborApp?.getState?.()||null;}catch{return null;}}
  function activeAnimalId(){const raw=clean(root.location?.hash).replace(/^#/,""),parts=raw.split("/");if(parts[0]!=="animal"||!parts[1])return"";try{return decodeURIComponent(parts[1]);}catch{return parts[1];}}
  function animalById(state,id){return(Array.isArray(state?.animals)?state.animals:[]).find(row=>String(row.id)===String(id))||null;}
  function isRabbit(animal){return lower(animal?.species).startsWith("rabbit");}
  function toneClass(tone){return["proven","strong","inferred","predicted","unknown"].includes(tone)?`is-${tone}`:"is-unknown";}
  function outcomeText(row){const outcomes=Array.isArray(row?.possibleGenotypes)?row.possibleGenotypes:[];return outcomes.length?outcomes.map(item=>`${esc(item.genotype)} ${pct(item.probability)}`).join(" · "):"No inheritance prediction available.";}
  function locusRow(row){const conflict=row.conflictCount?`<span class="hh-gv2-conflict">${row.conflictCount} conflict${row.conflictCount===1?"":"s"}</span>`:"";const note=row.note?`<small>${esc(row.note)}</small>`:row.evidenceCount?`<small>${row.evidenceCount} evidence record${row.evidenceCount===1?"":"s"}</small>`:"<small>No evidence recorded yet.</small>";return`<article class="hh-gv2-locus ${toneClass(row.tier.tone)}"><div class="hh-gv2-locus-code"><strong>${esc(row.locus)}</strong><span>${esc(row.genotype)}</span></div><div class="hh-gv2-locus-copy"><strong>${esc(row.name)}</strong><div><span class="hh-gv2-badge ${toneClass(row.tier.tone)}">${esc(row.tier.label)}</span>${conflict}</div>${note}</div></article>`;}
  function inheritanceRow(row){const label=row.supported?"Derived from parents":row.exact?"Exact outcome, evidence still limited":"Prediction only";const detail=row.exact&&row.genotype?`${esc(row.genotype.join("/"))} · 100% from recorded parent genotypes`:outcomeText(row);return`<article class="hh-gv2-inherit-row ${row.supported?"is-supported":"is-predicted"}"><div><strong>${esc(row.locus)} — ${esc(row.locusName)}</strong><small>${detail}</small></div><span>${esc(label)}</span></article>`;}
  function buildPanel(state,animal){
    const summary=Core.animalEvidenceSummary(animal);if(!summary.supported)return"";
    const inheritance=Core.inheritanceForAnimal(state,animal.id),interesting=summary.loci.filter(row=>row.resolved||row.evidenceCount||row.conflictCount);
    const lociHtml=interesting.length?interesting.map(locusRow).join(""):`<div class="hh-gv2-empty"><strong>No evidence-backed loci yet.</strong><span>Record phenotype, parent genetics, offspring outcomes, pedigree evidence, or a genetic test and HerdHarbor will build the evidence trail here.</span></div>`;
    const parents=inheritance.parent1&&inheritance.parent2;
    const parentHtml=parents?`<section class="hh-gv2-block"><div class="hh-gv2-block-head"><div><h4>Automatic offspring inheritance</h4><p>${esc(inheritance.parent1.name||"Dam")} × ${esc(inheritance.parent2.name||"Sire")}</p></div><span>${inheritance.rows.length} calculable loci</span></div>${inheritance.rows.length?`<div class="hh-gv2-inheritance">${inheritance.rows.map(inheritanceRow).join("")}</div>`:`<div class="hh-gv2-empty compact"><strong>Parent genotypes are not resolved enough yet.</strong><span>HerdHarbor will calculate inheritance automatically as parent evidence improves.</span></div>`}</section>`:"";
    const conflictNotice=summary.counts.conflicts?`<div class="hh-gv2-warning"><strong>${summary.counts.conflicts} genetics evidence conflict${summary.counts.conflicts===1?"":"s"} need review.</strong><span>HerdHarbor kept the stronger/current evidence instead of silently changing the genotype.</span></div>`:"";
    return`<section class="hh-gv2-panel" data-hh-gv2-panel><div class="hh-gv2-head"><div><span class="eyebrow">Genetics V2 · Phase 1</span><h3>Evidence & inheritance</h3><p>HerdHarbor separates what is proven, inferred, and merely predicted—and learns from parents and offspring without making you re-enter the same genetics.</p></div><button type="button" class="button button-ghost button-small" data-hh-gv2-open-editor>Open genetics editor</button></div><div class="hh-gv2-stats"><div><span>Evidence-backed loci</span><strong>${summary.counts.evidenceBacked} / ${Core.DISPLAY_LOCI.length}</strong></div><div><span>Resolved genotypes</span><strong>${summary.counts.resolved}</strong></div><div><span>DNA / offspring proven</span><strong>${summary.counts.proven}</strong></div><div><span>Conflicts</span><strong>${summary.counts.conflicts}</strong></div></div>${conflictNotice}<section class="hh-gv2-block"><div class="hh-gv2-block-head"><div><h4>Current genetic evidence</h4><p>Evidence strength is not an offspring probability. It describes how the recorded genotype is supported.</p></div></div><div class="hh-gv2-loci">${lociHtml}</div></section>${parentHtml}<div class="hh-gv2-rule"><strong>Prediction stays prediction.</strong><span>A possible genotype is not written as confirmed just because it is statistically likely. Phenotype, pedigree, offspring, or testing must resolve it.</span></div></section>`;
  }
  function renderProfile(){Core=root.HerdHarborGeneticsV2Phase1Core||Core;if(!Core)return false;const panel=root.document.querySelector('#view-animal-profile.active [data-hh-p2-panel="genetics"]');if(!panel)return false;const state=stateNow(),animal=animalById(state,activeAnimalId()),existing=panel.querySelector("[data-hh-gv2-panel]");if(!animal||!isRabbit(animal)){existing?.remove();return false;}const holder=root.document.createElement("div");holder.innerHTML=buildPanel(state,animal);const next=holder.firstElementChild;if(!next)return false;if(existing&&existing.innerHTML===next.innerHTML)return true;if(existing)existing.replaceWith(next);else panel.appendChild(next);return true;}
  function scheduleUI(){if(uiQueued)return;uiQueued=true;(root.requestAnimationFrame||root.setTimeout)(()=>{uiQueued=false;renderProfile();},0);}
  function propagate(){propagationTimer=null;if(propagationRunning)return;Core=root.HerdHarborGeneticsV2Phase1Core||Core;const app=root.HerdHarborApp,state=stateNow();if(!Core||!app?.commitState||!state){if(retryCount<16){retryCount+=1;schedulePropagation(350);}return;}retryCount=0;propagationRunning=true;try{const result=Core.propagateState(state,new Date().toISOString());if(result.changed){app.commitState(result.state,"");app.refresh?.();try{root.dispatchEvent(new root.CustomEvent("herdharbor:genetics-v2-updated",{detail:{updatedAnimalIds:result.updatedAnimalIds,evidenceCreated:result.evidenceCreated}}));}catch{}}}finally{propagationRunning=false;scheduleUI();}}
  function schedulePropagation(delay=120){if(propagationTimer)root.clearTimeout(propagationTimer);propagationTimer=root.setTimeout(propagate,delay);}
  function onClick(event){const open=event.target.closest?.("[data-hh-gv2-open-editor]");if(open){event.preventDefault();root.document.querySelector('#view-animal-profile.active [data-hh-p2-action="genetics"]')?.click();return;}if(event.target.closest?.("#gv2-save"))root.setTimeout(()=>schedulePropagation(0),180);}
  function install(){root.addEventListener("click",onClick,true);root.document.addEventListener("submit",()=>root.setTimeout(()=>schedulePropagation(0),160),true);["herdharbor:app-ready","herdharbor:offspring-auto-created","herdharbor:litter-workspace-changed","herdharbor:lifecycle-integrity-repaired","hashchange","storage"].forEach(name=>root.addEventListener(name,()=>{schedulePropagation();scheduleUI();}));root.addEventListener("herdharbor:genetics-v2-updated",scheduleUI);observer=new root.MutationObserver(scheduleUI);if(root.document.body)observer.observe(root.document.body,{childList:true,subtree:true});schedulePropagation(300);scheduleUI();}
  root.HerdHarborGeneticsV2Phase1=Object.freeze({VERSION:"2.0.0-phase1",refresh(){schedulePropagation(0);scheduleUI();}});install();
})(typeof globalThis!=="undefined"?globalThis:this);