(function(root){
'use strict';
const Genetics=root.HerdHarborGeneticsPlatform,STORAGE_KEY='herdharbor_pre_alpha_v1';
if(!Genetics)return;
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return{}}};
const label=s=>Genetics.getAdapter(s)?.label||String(s||'Unknown species');
function statusBadge(adapter){return `<span class="hh-msg-badge ${adapter.status==='production'?'is-production':'is-foundation'}">${adapter.status==='production'?'Production engine':'Foundation ready'}</span>`;}
function capabilities(adapter){const labels={mendelian:'Mendelian',dominant:'Dominant',recessive:'Recessive',codominant:'Co-dominant',incompleteDominance:'Incomplete dominance',sexLinked:'Sex-linked',carrierStatus:'Carrier status',unknownPartial:'Partial genotype safety',pedigreeEvidence:'Pedigree evidence',pairingCompatibility:'Pairing compatibility',offspringPrediction:'Offspring predictions'};return Object.entries(adapter.capabilities||{}).filter(([,on])=>on).map(([id])=>`<span>${esc(labels[id]||id)}</span>`).join('');}
function rawEvidence(profile){const traits=Object.entries(profile.unmappedTraits||{}),loci=Object.entries(profile.unmappedLoci||{}),tests=profile.genomicTests||[];if(!traits.length&&!loci.length&&!tests.length)return'<p class="muted">No additional genetics records are stored for this animal yet.</p>';return `<div class="hh-msg-evidence">${traits.length?`<p><strong>${traits.length}</strong> unclassified trait record${traits.length===1?'':'s'} preserved without interpretation.</p>`:''}${loci.length?`<p><strong>${loci.length}</strong> unclassified locus record${loci.length===1?'':'s'} preserved without interpretation.</p>`:''}${tests.length?`<p><strong>${tests.length}</strong> DNA/genomic test record${tests.length===1?'':'s'} preserved.</p>`:''}</div>`;}
function foundationHtml(animal){const species=Genetics.canonicalSpecies(animal?.species),adapter=Genetics.getAdapter(species);if(!adapter)return'<p>No genetics adapter is registered for this species.</p>';const profile=Genetics.normalizeProfile(animal.genetics||{},species),traits=Genetics.listTraits(species,{breed:animal.breed}),loci=Genetics.listLoci(species);return `<div class="hh-msg-head"><div><span class="eyebrow">Alpha v1.7.1 · Shared genetics API</span><h2>${esc(label(species))} Genetics</h2><p>${esc(animal.breed||'Breed not recorded')}</p></div>${statusBadge(adapter)}</div><div class="hh-msg-callout"><strong>Architecture first.</strong><p>${esc(Genetics.adapterExplanation(adapter,{animal}))}</p></div><div class="hh-msg-facts"><div><small>Adapter</small><strong>${esc(adapter.version)}</strong></div><div><small>Reviewed loci</small><strong>${loci.length}</strong></div><div><small>Reviewed traits</small><strong>${traits.length}</strong></div><div><small>Chromosomes</small><strong>${esc(adapter.chromosomeSystem||'autosomal')}</strong></div></div><h3>Shared engine capabilities</h3><div class="hh-msg-chips">${capabilities(adapter)}</div>${traits.length?`<h3>Registered traits</h3><div class="hh-msg-traits">${traits.map(t=>`<details><summary>${esc(t.name)}</summary><p>${esc(t.traitType)} · ${esc(t.inheritanceModel)}</p><small>${esc(t.scientificStatus)}</small></details>`).join('')}</div>`:`<div class="hh-msg-callout"><strong>No species-specific gene library bundled yet.</strong><p>This is intentional for v1.7.1. The adapter, registries, inheritance contract, evidence model, and prediction plumbing are ready; reviewed ${esc(label(species).toLowerCase())} genetics content comes in ${esc(adapter.nextRelease||'a later release')}.</p></div>`}<h3>Existing records</h3>${rawEvidence(profile)}<p class="muted">Unknown and partial genetics stay unknown. HerdHarbor does not manufacture inheritance percentages from missing data.</p>`;}
function dialog(title,html){document.querySelector('#hh-multispecies-genetics-dialog')?.remove();const d=document.createElement('div');d.id='hh-multispecies-genetics-dialog';d.className='modal-overlay active hh-msg-overlay';d.innerHTML=`<section class="modal hh-msg-modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-header"><strong>${esc(title)}</strong><button class="icon-button" type="button" data-msg-close aria-label="Close">×</button></div><div class="modal-content">${html}</div></section>`;(document.body||document.documentElement).appendChild(d);d.querySelector('[data-msg-close]')?.addEventListener('click',()=>d.remove());d.addEventListener('click',e=>{if(e.target===d)d.remove()});return d;}
function open(animalId){const state=read(),animal=(state.animals||[]).find(a=>String(a.id)===String(animalId));if(!animal)return null;const species=Genetics.canonicalSpecies(animal.species);if(species==='rabbit'){const openers=[()=>root.HerdHarborRabbitGeneticsV2?.openProfile?.(animal.id),()=>root.HerdHarborBreedingIntelligence?.openGeneticProfile?.(animal.id)];for(const fn of openers){try{const result=fn();if(result!==undefined||document.querySelector('.hh-bi-modal-backdrop'))return result??true;}catch{}}}return dialog(`${animal.name||'Animal'} Genetics`,foundationHtml(animal));}
root.HerdHarborMultiSpeciesGeneticsUI=Object.freeze({version:'1.7.1',open,render:foundationHtml});
})(window);
