(function(root,factory){const rabbit=typeof module==='object'&&module.exports?require('./rabbit-genetics-v1.6.1.js'):root.HerdHarborRabbitGenetics;const api=factory(rabbit);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.HerdHarborGeneticsPlatform=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Rabbit){
'use strict';
const VERSION='1.6.1',SPECIES_RULE_VERSION='2026.1',UNKNOWN='_';
const TRAIT_TYPES=Object.freeze({MENDELIAN:'mendelian',SEX_LINKED:'sex-linked',GENOMIC:'genomic-marker',COMPLEX:'complex',POLYGENIC:'polygenic',QUANTITATIVE:'quantitative'});
const EVIDENCE_PRIORITY=Object.freeze({unknown:0,possible:1,'phenotype-inferred':2,'pedigree-inferred':3,'breeder-confirmed':4,'parent-confirmed':5,'offspring-confirmed':6,'dna-confirmed':7});
const SCIENTIFIC_STATUS=Object.freeze({MOLECULAR:'molecularly-confirmed',CLASSICAL:'strong-classical-genetics',COMPLEX:'complex-modifier',OBSERVATIONAL:'observational-experimental'});
const speciesModules=new Map();
const clean=v=>String(v==null?'':v).trim(),key=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),clone=v=>JSON.parse(JSON.stringify(v));
const canonicalSpecies=v=>({rabbits:'rabbit',rabbit:'rabbit',cattle:'cattle',cow:'cattle',cows:'cattle',goat:'goat',goats:'goat',sheep:'sheep',poultry:'poultry',chicken:'poultry',chickens:'poultry',pig:'pig',pigs:'pig',swine:'pig'}[clean(v).toLowerCase()]||key(v));
function registerSpecies(value){if(!value?.species||!Array.isArray(value.traits))throw new Error('Species rules require species and traits.');const species=canonicalSpecies(value.species),traits=new Map();value.traits.forEach(t=>{if(!t.id||!t.traitType||!t.inheritanceModel)throw new Error(`Invalid trait in ${species}.`);traits.set(key(t.id),Object.freeze({...clone(t),id:key(t.id),species,breedApplicability:(t.breedApplicability||['*']).map(v=>v==='*'?'*':key(v))}));});const module=Object.freeze({...clone(value),species,version:value.version||SPECIES_RULE_VERSION,traits});speciesModules.set(species,module);return module;}
function getSpeciesModule(species){return speciesModules.get(canonicalSpecies(species))||null;}
function applicableTraits(species,breed){const module=getSpeciesModule(species),b=key(breed||'unknown');if(!module)return[];return [...module.traits.values()].filter(t=>t.breedApplicability.includes('*')||t.breedApplicability.includes(b)).map(clone);}
function normalizeProfile(input={},species=input.species){const s=canonicalSpecies(species),module=getSpeciesModule(s),records={};if(module)[...module.traits.values()].forEach(t=>{const old=input.traits?.[t.id]||{};records[t.id]={status:old.status||'unknown',alleles:Array.isArray(old.alleles)?old.alleles.slice():[],markers:Array.isArray(old.markers)?clone(old.markers):[],value:old.value??null,unit:old.unit||'',source:old.source||'',confidence:old.confidence??null,provenance:Array.isArray(old.provenance)?clone(old.provenance):[]};});return{schemaVersion:3,geneticsEngineVersion:VERSION,speciesRuleVersion:module?.version||null,species:s,breedId:key(input.breedId||input.breed||''),traits:records,genomicTests:Array.isArray(input.genomicTests)?clone(input.genomicTests):[],quantitativeValues:Array.isArray(input.quantitativeValues)?clone(input.quantitativeValues):[],evidence:Array.isArray(input.evidence)?clone(input.evidence):[],conflicts:Array.isArray(input.conflicts)?clone(input.conflicts):[],history:Array.isArray(input.history)?clone(input.history):[]};}
function crossDiploid(def,a,b){if(!Array.isArray(a)||!Array.isArray(b)||a.length!==2||b.length!==2||[...a,...b].every(x=>x!==UNKNOWN)===false)return{mode:'uncertain',outcomes:[],missing:['Both parental genotypes are required.']};const rank=x=>def.alleles.indexOf(x),sort=p=>p.slice().sort((x,y)=>rank(x)-rank(y)),map=new Map();a.forEach(x=>b.forEach(y=>{const p=sort([x,y]),k=p.join('/');map.set(k,(map.get(k)||0)+.25);}));return{mode:'exact',outcomes:[...map].map(([genotype,probability])=>({genotype:genotype.split('/'),probability,phenotype:def.phenotypeRules?.[genotype]||def.phenotypeRules?.[genotype.split('/').reverse().join('/')]||'Genotype recorded'}))};}
function crossSexLinked(def,sire,dam){if(!Array.isArray(sire)||sire.length!==2||!Array.isArray(dam)||dam.length!==2||[...sire,...dam].includes(UNKNOWN))return{mode:'uncertain',outcomes:[],missing:['Known sire ZZ and dam ZW records are required.']};const sireZ=sire,damZ=dam.find(a=>a!=='W');if(!dam.includes('W')||!damZ)return{mode:'invalid',outcomes:[],notice:'Poultry dam must use a Z/W genotype.'};const rows=[];sireZ.forEach(z=>{rows.push({sex:'male',chromosomes:[z,damZ],probability:.25});rows.push({sex:'female',chromosomes:[z,'W'],probability:.25});});return{mode:'exact-sex-linked',outcomes:rows.map(r=>({...r,phenotype:def.phenotypeRules?.[`${r.sex}:${r.chromosomes[0]}`]||'Sex-linked genotype recorded'}))};}
function analyzeTrait(def,a,b){if(def.traitType===TRAIT_TYPES.QUANTITATIVE)return{mode:'quantitative',parentValues:[a.value??null,b.value??null],unit:a.unit||b.unit||def.unit||'',dataSource:[a.source||null,b.source||null],confidence:[a.confidence??null,b.confidence??null],notice:'Breeding values are not Mendelian probabilities.'};if([TRAIT_TYPES.COMPLEX,TRAIT_TYPES.POLYGENIC,TRAIT_TYPES.GENOMIC].includes(def.traitType))return{mode:def.traitType,probabilities:false,notice:'This trait is recorded without unsupported Mendelian percentages.',parentRecords:[clone(a),clone(b)]};if(def.traitType===TRAIT_TYPES.SEX_LINKED)return crossSexLinked(def,a.alleles,b.alleles);return crossDiploid(def,a.alleles,b.alleles);}
function conditionNotice(def,result){if(!def.condition||result.mode!=='exact')return null;const affected=result.outcomes.find(o=>o.phenotype==='Affected');if(!affected)return null;return{severity:'warning',traitId:def.id,title:'Carrier × Carrier',message:'Both animals can produce offspring affected by the same recorded recessive condition. Review the expected outcomes before breeding.',probability:affected.probability};}
function analyzePairing(parent1,parent2,context={}){const species=canonicalSpecies(parent1?.species),other=canonicalSpecies(parent2?.species);if(!species||species!==other)return{supported:false,reason:'Both animals must be the same supported species.'};if(species==='rabbit'){if(!Rabbit)return{supported:false,reason:'Rabbit genetics module unavailable.'};return Rabbit.analyzePairing(parent1,parent2,context);}const module=getSpeciesModule(species);if(!module)return{supported:false,reason:`No genetics rules are registered for ${species}.`};const p1=normalizeProfile(parent1.genetics||{},species),p2=normalizeProfile(parent2.genetics||{},species),breed=key(parent1.breed||p1.breedId||parent2.breed||p2.breedId||''),analyses=[],notices=[];applicableTraits(species,breed).forEach(def=>{const result=analyzeTrait(def,p1.traits[def.id],p2.traits[def.id]);const notice=conditionNotice(def,result);if(notice)notices.push(notice);analyses.push({traitId:def.id,traitName:def.name,traitType:def.traitType,inheritanceModel:def.inheritanceModel,scientificStatus:def.scientificStatus,result});});return{supported:true,geneticsEngineVersion:VERSION,speciesRuleVersion:module.version,species,breedContext:breed||'species-level',analyses,notices,unknowns:analyses.filter(x=>x.result.mode==='uncertain').map(x=>x.traitId),monitoring:{species,breedId:breed||null,traitIds:analyses.map(x=>x.traitId),calculationStage:'complete'}};}
function applyEvidence(profile,item){const out=normalizeProfile(profile,profile.species),record=out.traits[key(item.traitId)];if(!record)return out;const oldRank=EVIDENCE_PRIORITY[record.status]||0,newRank=EVIDENCE_PRIORITY[item.status]||0;if(newRank<oldRank&&item.value!==undefined&&JSON.stringify(item.value)!==JSON.stringify(record.alleles))out.conflicts.push({traitId:item.traitId,existing:clone(record),incoming:clone(item),resolution:'review-required',createdAt:new Date().toISOString()});else if(newRank>=oldRank){const old=clone(record);if(item.alleles)record.alleles=clone(item.alleles);if(item.value!==undefined)record.value=item.value;record.status=item.status;record.source=item.source||record.source;record.confidence=item.confidence??record.confidence;out.history.push({at:new Date().toISOString(),traitId:item.traitId,oldState:old,newState:clone(record),reason:item.reason||'evidence-applied'});}record.provenance.push({at:new Date().toISOString(),...clone(item)});out.evidence.push({at:new Date().toISOString(),...clone(item)});return out;}
function pedigreeEvidence(animal,animals=[],traitId,maxDepth=5){const byId=new Map(animals.map(a=>[String(a.id),a])),rows=[];function walk(id,depth,relationship){if(!id||depth>maxDepth)return;const relative=byId.get(String(id));if(!relative||canonicalSpecies(relative.species)!==canonicalSpecies(animal.species))return;const profile=normalizeProfile(relative.genetics||{},relative.species),record=profile.traits[key(traitId)];if(record&&(record.status!=='unknown'||record.alleles.length||record.value!=null))rows.push({traitId:key(traitId),relatedAnimalId:relative.id,relationship,depth,status:'pedigree-inferred',record:clone(record)});walk(relative.sireId,depth+1,`${relationship} sire`);walk(relative.damId,depth+1,`${relationship} dam`);}walk(animal.sireId,1,'sire');walk(animal.damId,1,'dam');return rows;}
function offspringEvidenceForParents(parent1,parent2,offspring=[],traitId){const species=canonicalSpecies(parent1?.species),def=getSpeciesModule(species)?.traits.get(key(traitId));if(!def||def.traitType!==TRAIT_TYPES.MENDELIAN||!def.condition)return[];const recessive=def.alleles[1],proof=(offspring||[]).filter(child=>{const r=normalizeProfile(child.genetics||{},species).traits[def.id];return r?.alleles?.length===2&&r.alleles.every(a=>a===recessive);});if(!proof.length)return[];return[parent1,parent2].map(parent=>({traitId:def.id,allele:recessive,status:'offspring-confirmed',source:'offspring',relatedAnimalIds:proof.map(x=>x.id),reason:`Affected offspring establish that ${parent.name||'the parent'} supplied ${recessive}.`}));}
const trait=(id,name,traitType,inheritanceModel,options={})=>({id,name,traitType,inheritanceModel,scientificStatus:options.scientificStatus||SCIENTIFIC_STATUS.CLASSICAL,breedApplicability:options.breeds||['*'],alleles:options.alleles||[],phenotypeRules:options.phenotypeRules||{},condition:Boolean(options.condition),unit:options.unit||''});
registerSpecies({species:'Cattle',traits:[trait('extension-red-black','Black/red extension',TRAIT_TYPES.MENDELIAN,'autosomal-dominant',{breeds:['angus','red-angus'],alleles:['E','e'],phenotypeRules:{'E/E':'Black','E/e':'Black carrier of red','e/e':'Red'}}),trait('polled','Polled/horned',TRAIT_TYPES.MENDELIAN,'breed-population-specific',{breeds:['angus','red-angus','hereford'],alleles:['P','p'],phenotypeRules:{'P/P':'Homozygous polled','P/p':'Heterozygous polled','p/p':'Horned'}}),trait('recessive-condition','Breed-specific recessive condition',TRAIT_TYPES.MENDELIAN,'autosomal-recessive',{condition:true,alleles:['N','a'],phenotypeRules:{'N/N':'Clear','N/a':'Carrier','a/a':'Affected'}}),trait('epd-growth','Growth EPD',TRAIT_TYPES.QUANTITATIVE,'breed-evaluation',{unit:'breed units'})]});
registerSpecies({species:'Goat',traits:[trait('coat-system','Canonical goat pigmentation',TRAIT_TYPES.COMPLEX,'species-and-breed-specific'),trait('polled','Polled/horned',TRAIT_TYPES.COMPLEX,'goat-specific',{scientificStatus:SCIENTIFIC_STATUS.COMPLEX}),trait('recessive-condition','Breed-specific recessive condition',TRAIT_TYPES.MENDELIAN,'autosomal-recessive',{condition:true,alleles:['N','a'],phenotypeRules:{'N/N':'Clear','N/a':'Carrier','a/a':'Affected'}}),trait('production-index','Production breeding value',TRAIT_TYPES.QUANTITATIVE,'breed-evaluation',{unit:'breed units'})]});
registerSpecies({species:'Sheep',traits:[trait('prnp','PRNP scrapie genotype',TRAIT_TYPES.GENOMIC,'tested-haplotype',{alleles:['ARR','ARQ','VRQ'],scientificStatus:SCIENTIFIC_STATUS.MOLECULAR}),trait('prolificacy','Breed-supported prolificacy variant',TRAIT_TYPES.GENOMIC,'variant-specific',{breeds:['booroola-merino','belclare','cambridge'],scientificStatus:SCIENTIFIC_STATUS.MOLECULAR}),trait('recessive-condition','Breed-specific recessive condition',TRAIT_TYPES.MENDELIAN,'autosomal-recessive',{condition:true,alleles:['N','a'],phenotypeRules:{'N/N':'Clear','N/a':'Carrier','a/a':'Affected'}}),trait('growth-ebv','Growth EBV',TRAIT_TYPES.QUANTITATIVE,'breed-evaluation',{unit:'breed units'})]});
registerSpecies({species:'Poultry',sexChromosomes:{male:'ZZ',female:'ZW'},traits:[trait('barring','Z-linked barring',TRAIT_TYPES.SEX_LINKED,'avian-z-linked',{alleles:['B','b','W'],phenotypeRules:{'male:B':'Barred male-associated phenotype','male:b':'Non-barred male-associated phenotype','female:B':'Barred female-associated phenotype','female:b':'Non-barred female-associated phenotype'}}),trait('silver-gold','Z-linked silver/gold',TRAIT_TYPES.SEX_LINKED,'avian-z-linked',{alleles:['S','s','W']}),trait('blue','Blue/splash dilution',TRAIT_TYPES.MENDELIAN,'incomplete-dominance',{alleles:['Bl','bl'],phenotypeRules:{'Bl/Bl':'Splash','Bl/bl':'Blue','bl/bl':'Black'}}),trait('comb','Comb interaction',TRAIT_TYPES.COMPLEX,'multi-locus-interaction'),trait('egg-color','Egg color',TRAIT_TYPES.POLYGENIC,'complex-marker-and-background') ]});
registerSpecies({species:'Pig',traits:[trait('coat-system','Canonical pig coat genetics',TRAIT_TYPES.COMPLEX,'species-and-breed-specific'),trait('recessive-condition','Breed-specific recessive condition',TRAIT_TYPES.MENDELIAN,'autosomal-recessive',{condition:true,alleles:['N','a'],phenotypeRules:{'N/N':'Clear','N/a':'Carrier','a/a':'Affected'}}),trait('growth-index','Growth breeding value',TRAIT_TYPES.QUANTITATIVE,'breed-evaluation',{unit:'breed units'})]});
return Object.freeze({VERSION,SPECIES_RULE_VERSION,TRAIT_TYPES,EVIDENCE_PRIORITY,SCIENTIFIC_STATUS,canonicalSpecies,registerSpecies,getSpeciesModule,applicableTraits,normalizeProfile,analyzePairing,applyEvidence,pedigreeEvidence,offspringEvidenceForParents,crossDiploid,crossSexLinked});
});
