(function(root){
'use strict';
const Standards=root.HerdHarborStandards,Genetics=root.HerdHarborGeneticsPlatform,STORAGE_KEY='herdharbor_pre_alpha_v1';
if(!Standards||!Genetics)return;
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return{}}};
const species=v=>Genetics.canonicalSpecies(v);
const rabbit=a=>species(a?.species)==='rabbit';
function dialog(title,html){document.querySelector('#hh-phase3-dialog')?.remove();const d=document.createElement('div');d.id='hh-phase3-dialog';d.className='modal-overlay active';d.innerHTML=`<section class="modal hh-phase3-modal" role="dialog" aria-modal="true"><div class="modal-header"><div><span class="eyebrow">HerdHarbor Phase 3</span><h2>${esc(title)}</h2></div><button class="icon-button" data-phase3-close aria-label="Close">×</button></div><div class="modal-content">${html}</div></section>`;(document.body||document.documentElement).appendChild(d);d.querySelector('[data-phase3-close]').addEventListener('click',()=>d.remove());d.addEventListener('click',e=>{if(e.target===d)d.remove()});return d;}
function standardHtml(standard){if(!standard)return`<div class="hh-phase3-unavailable"><strong>ARBA reference temporarily unavailable</strong><p>Your HerdHarbor show records are unaffected.</p></div>`;const s=Standards.applyCorrections(standard);return`<div class="hh-phase3-standard-head"><span class="badge">${esc(s.status)}</span><h3>${esc(s.breedName)}</h3><p>ARBA · ${esc(s.edition)}</p></div>${s.status!=='recognized'?'<p class="hh-phase3-warning">This is not an established recognized standard.</p>':''}<div class="hh-phase3-sections">${s.sections.map(x=>`<details><summary>${esc(x.title)}</summary><p>${esc(x.summary)}</p></details>`).join('')}</div><p class="muted">${esc(s.licensing.notice)}</p><p class="muted">Source: ${esc(s.source.sourceType)} · Last verified ${esc(s.source.lastVerified||'not recorded')}</p>`;}
function openStandard({breed='',edition='',date='',animalId='',entryId=''}={}){const state=read();let animal=animalId?state.animals?.find(a=>String(a.id)===String(animalId)):null;if(entryId){const entry=state.showEntries?.find(e=>String(e.id)===String(entryId));animal=state.animals?.find(a=>String(a.id)===String(entry?.animalId));const show=state.shows?.find(s=>String(s.id)===String(entry?.showId));date=date||show?.startDate||'';edition=edition||entry?.standardEdition||show?.standardEdition||'';}breed=breed||animal?.breed||'';let standard;try{standard=Standards.resolve({species:'Rabbit',registry:'arba',breedName:breed,edition,date});}catch{return dialog('ARBA Standards & Judging',standardHtml(null));}const d=dialog('ARBA Standards & Judging',`<div class="hh-phase3-search"><input data-phase3-search placeholder="Search ${esc(breed||'rabbit')} standards" value=""><label><input type="checkbox" data-phase3-global> Search all rabbit standards</label></div><div data-phase3-results>${standardHtml(standard)}</div>`);const input=d.querySelector('[data-phase3-search]'),host=d.querySelector('[data-phase3-results]');input.addEventListener('input',()=>{const q=input.value.trim();if(!q){host.innerHTML=standardHtml(standard);return;}const rows=Standards.search(q,{breedId:breed,global:d.querySelector('[data-phase3-global]').checked});host.innerHTML=rows.length?rows.map(r=>`<button class="hh-phase3-result" data-standard-id="${esc(r.standardId)}"><strong>${esc(r.breedName)} · ${esc(r.section.title)}</strong><span>${esc(r.section.summary)}</span><small>${esc(r.edition)} · ${esc(r.status)}</small></button>`).join(''):'<p>No matching structured summaries are available.</p>';});return d;}
function geneticsHtml(animal){const s=species(animal?.species);if(s==='rabbit'){const g=root.HerdHarborRabbitGenetics?.normalizeGenetics(animal.genetics);return`<p>Rabbit genetics remains powered by the v1.6.1 engine.</p><p><strong>Tracked loci:</strong> ${Object.keys(g?.loci||{}).length}</p><button class="button button-primary" data-open-rabbit-profile="${esc(animal.id)}">Open rabbit genetic profile</button>`;}const module=Genetics.getSpeciesModule(s);if(!module)return'<p>No genetics module is registered for this species.</p>';const profile=Genetics.normalizeProfile(animal.genetics||{},s),traits=Genetics.applicableTraits(s,animal.breed);return`<div class="hh-phase3-genetics-head"><span class="badge">${esc(s)}</span><p>${esc(animal.breed||'Crossbreed / unknown breed')} · Rule set ${esc(module.version)}</p></div><h3>Known Genetics</h3><div class="hh-phase3-traits">${traits.map(t=>{const r=profile.traits[t.id];return`<details><summary><strong>${esc(t.name)}</strong><span>${esc(r.status||'unknown')}</span></summary><p>${esc(t.traitType)} · ${esc(t.inheritanceModel)}</p>${t.traitType==='quantitative'?`<p>Breeding value: ${r.value==null?'Unknown':esc(r.value)} ${esc(r.unit||t.unit||'')}</p>`:`<p>Genotype/marker: ${r.alleles?.length?esc(r.alleles.join('/')):'Unknown'}</p>`}<small>${esc(t.scientificStatus)}</small></details>`}).join('')}</div><h3>DNA / genomic tests</h3>${profile.genomicTests.length?profile.genomicTests.map(t=>`<p><strong>${esc(t.testName||t.marker)}</strong> — ${esc(t.result)} · ${esc(t.laboratory||'Source not recorded')}</p>`).join(''):'<p class="muted">No structured tests recorded.</p>'}<p class="muted">Unknown values remain unknown. Quantitative values are never shown as Mendelian percentages.</p>`;}
function openGenetics(animalId){const a=read().animals?.find(x=>String(x.id)===String(animalId));if(!a)return null;const d=dialog(`${a.name||'Animal'} Genetics`,geneticsHtml(a));d.querySelector('[data-open-rabbit-profile]')?.addEventListener('click',()=>{d.remove();root.HerdHarborBreedingIntelligence?.openGeneticProfile?.(a.id)});return d;}
function addShowsResources(){const host=document.querySelector('#view-shows.active');if(!host||host.querySelector('[data-phase3-rabbit-resources]'))return;const state=read(),hasRabbit=(state.animals||[]).some(rabbit),rabbitContext=hasRabbit||/rabbit/i.test(host.textContent||'');if(!rabbitContext)return;const panel=document.createElement('section');panel.className='panel hh-phase3-resources';panel.dataset.phase3RabbitResources='';panel.innerHTML='<div class="panel-header"><div><h3>Rabbit Resources</h3><small>Optional registry references; show records work independently.</small></div><button class="button button-ghost" data-phase3-standard>ARBA Standards & Judging</button></div>';const anchor=host.querySelector('.hh-shows-toolbar,.stats-grid,.hh-shows-filter-grid')?.closest('section,div');anchor?.insertAdjacentElement('afterend',panel)||host.appendChild(panel);}
function addContextButtons(){const state=read();document.querySelectorAll('.hh-show-entry-row:not([data-phase3-ready])').forEach(row=>{row.dataset.phase3Ready='';const name=row.querySelector('.list-item-main strong')?.textContent?.split(' · ')[0]?.trim(),animal=(state.animals||[]).find(a=>(a.name||'').trim()===name);if(!rabbit(animal))return;const actions=row.querySelector('.list-item-actions');if(actions){const b=document.createElement('button');b.className='button button-ghost button-small';b.textContent='View ARBA Standard';b.dataset.phase3Standard='';b.dataset.animalId=animal.id;actions.prepend(b);}});const modal=document.querySelector('#modal');if(modal&&!modal.querySelector('[data-phase3-animal-genetics]')){const title=modal.querySelector('.modal-header h2')?.textContent?.trim(),animal=(state.animals||[]).find(a=>(a.name||'').trim()===title),actions=modal.querySelector('.modal-actions');if(animal&&actions){const g=document.createElement('button');g.className='button button-ghost';g.textContent='View genetics';g.dataset.phase3AnimalGenetics=animal.id;actions.insertBefore(g,actions.lastElementChild);if(rabbit(animal)){const b=document.createElement('button');b.className='button button-ghost';b.textContent='View ARBA Standard';b.dataset.phase3Standard='';b.dataset.animalId=animal.id;actions.insertBefore(b,actions.lastElementChild);}}}}
document.addEventListener('click',e=>{const standard=e.target.closest('[data-phase3-standard]');if(standard){e.preventDefault();openStandard({animalId:standard.dataset.animalId||'',entryId:standard.dataset.entryId||''});return;}const genetics=e.target.closest('[data-phase3-animal-genetics]');if(genetics){e.preventDefault();openGenetics(genetics.dataset.phase3AnimalGenetics);}});
const refresh=()=>{try{addShowsResources();addContextButtons();}catch(error){root.HerdHarborMonitoring?.captureError?.(error,{module:'standards-and-genetics',errorCategory:'optional_module_failure',metadata:{calculationStage:'ui-refresh'}});}};
const start=()=>{refresh();const target=document.body;if(target){const observer=new MutationObserver(refresh);observer.observe(target,{childList:true,subtree:true});root.__hhPhase3Observer=observer;}window.addEventListener('hashchange',refresh);};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
root.HerdHarborPhase3=Object.freeze({version:'phase3.1',openStandard,openGenetics,refresh});
})(window);
