(function(root,factory){const Base=(typeof module==='object'&&module.exports)?require('./rabbit-genetics-engine-v2.js'):root.HerdHarborBreedingIntelligenceCore;const api=factory(Base||{});if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.HerdHarborBreedingIntelligenceCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Base){
'use strict';
const RELEASE_VERSION='1.4.5';
const ENGINE_VERSION='2.1.0';
const LOCI=Base.RABBIT_LOCI;
const DISPLAY=Base.DISPLAY_LOCI||['A','B','C','D','E','En','V'];
const clean=v=>String(v==null?'':v).trim();
const norm=v=>clean(v).toLowerCase().replace(/[()]/g,' ').replace(/\s+/g,' ').trim();
const pairKey=(l,p)=>Base.normalizeGenetics({loci:{[l]:{alleles:p}}}).loci[l].alleles.join('/');
const exactPair=(a,b)=>a.length===b.length&&a.every((v,i)=>v===b[i]);
const rangeText=(a,b)=>Math.abs(a-b)<1e-9?`${Math.round(a*10000)/100}%`:`${Math.round(a*10000)/100}%–${Math.round(b*10000)/100}%`;
function intersection(a,b,l){const keys=new Set(b.map(p=>pairKey(l,p)));return a.filter(p=>keys.has(pairKey(l,p)));}
function phenotypePairs(animal,locus){
  let list=Base.possiblePairsForLocus(animal,animal?.color||animal?.variety,locus);
  const c=norm(animal?.color||animal?.variety);
  if(/magpie/.test(c)){
    if(locus==='E') list=list.filter(p=>['ej/ej','ej/e'].includes(pairKey('E',p)));
    if(locus==='C') list=list.filter(p=>{const q=Base.normalizeGenetics({loci:{C:{alleles:p}}}).loci.C.alleles;return q[0]==='cchd'&&q[1]!=='C';});
  }
  if(/harlequin|tricolor|tri color|tri-color/.test(c)&&!/magpie/.test(c)){
    if(locus==='E') list=list.filter(p=>['ej/ej','ej/e'].includes(pairKey('E',p)));
    if(locus==='C') list=list.filter(p=>Base.normalizeGenetics({loci:{C:{alleles:p}}}).loci.C.alleles[0]==='C');
  }
  if(/^(black|blue|chocolate|lilac)(\s|$)/.test(c.replace(/^(broken|solid|booted|charlie)\s+/,''))&&!/tort|otter|steel|harlequin|magpie|chinchilla|point|sable|agouti|lynx|opal/.test(c)&&locus==='A') list=list.filter(p=>pairKey('A',p)==='a/a');
  if(/\b(blue|lilac|opal|squirrel|smoke pearl|cream)\b/.test(c)&&locus==='D') list=list.filter(p=>pairKey('D',p)==='d/d');
  if(/\b(chocolate|lilac)\b/.test(c)&&locus==='B') list=list.filter(p=>pairKey('B',p)==='b/b');
  if(/\bre(?:d)?[- ]?eyed white\b|\brew\b/.test(c)&&locus==='C') list=list.filter(p=>pairKey('C',p)==='c/c');
  if(/\bblue[- ]?eyed white\b|\bbew\b/.test(c)&&locus==='V') list=list.filter(p=>pairKey('V',p)==='v/v');
  if(/^broken\b/.test(c)&&locus==='En') list=list.filter(p=>pairKey('En',p)==='En/en');
  if(/^charlie\b/.test(c)&&locus==='En') list=list.filter(p=>pairKey('En',p)==='En/En');
  return list.length?list:Base.possiblePairsForLocus(animal,animal?.color||animal?.variety,locus);
}
function canSupply(animal,locus,allele){return phenotypePairs(animal,locus).some(p=>p.includes(allele));}
function directConflict(animal){
  const g=Base.normalizeGenetics(animal?.genetics),out=[];
  for(const l of DISPLAY){
    const explicit=g.loci[l].alleles;
    if(!explicit.some(a=>a&&a!=='_'))continue;
    const phenotypeOnly={...animal,genetics:null};
    const valid=phenotypePairs(phenotypeOnly,l);
    const explicitOptions=Base.possiblePairsForLocus({genetics:{loci:{[l]:{alleles:explicit}}}},'',l);
    if(!intersection(valid,explicitOptions,l).length)out.push({type:'phenotype-genotype',animalId:animal.id,animalName:animal.name,locus:l,message:`Genetic conflict detected. ${animal.name||'This rabbit'}'s recorded color and ${l}-locus genotype do not agree. Review the color or genetics before relying on this prediction.`});
  }
  return out;
}
function recessiveRequirement(color){const c=norm(color);const out=[];if(/chocolate|lilac/.test(c))out.push(['B','b','Chocolate']);if(/blue|lilac|opal|squirrel|smoke pearl|cream/.test(c))out.push(['D','d','Dilute']);if(/red[- ]?eyed white|\brew\b/.test(c))out.push(['C','c','REW']);if(/blue[- ]?eyed white|\bbew\b/.test(c))out.push(['V','v','BEW']);if(/\btort\b/.test(c))out.push(['E','e','Non-extension']);return out;}
function offspringConflicts(animals){const by=new Map((animals||[]).map(a=>[String(a.id),a])),out=[];for(const child of animals||[]){const sire=by.get(String(child.sireId||'')),dam=by.get(String(child.damId||''));if(!sire||!dam)continue;for(const [l,a,label] of recessiveRequirement(child.color||child.variety)){if(!canSupply(sire,l,a)||!canSupply(dam,l,a))out.push({type:'offspring-parent',animalId:child.id,locus:l,message:`Genetic conflict detected. ${child.name||'Recorded offspring'} is recorded as ${child.color||child.variety}, but the recorded parents cannot both supply the required ${a} allele for ${label}. Review parentage, color, or genetics.`});}}
  return out;
}
function sourceStatus(record){const s=norm(record?.source);if(s==='dna'||s==='genetic-test')return'Known / Direct';if(s==='offspring')return'Proven by Offspring';if(s==='phenotype')return'Proven by Phenotype';if(s==='pedigree')return record?.status==='confirmed'?'Strongly Inferred':'Possible';if(s==='user'||s==='breeder')return'Known / Direct';if(record?.alleles?.some(a=>a&&a!=='_'))return'Possible';return'Unknown';}
function alleleEvidence(animal){const g=Base.normalizeGenetics(animal?.genetics),rows=[];for(const l of DISPLAY){const r=g.loci[l];rows.push({locus:l,genotype:r.alleles.join(''),status:sourceStatus(r),source:r.source||'unknown',note:r.note||''});}return rows;}
function ancestorCarrierEstimate(animal,animals,locus,allele,maxDepth=3){const by=new Map((animals||[]).map(a=>[String(a.id),a])),paths=[];function walk(id,depth,path){if(!id||depth>maxDepth)return;const a=by.get(String(id));if(!a)return;const opts=phenotypePairs(a,locus),allHomo=opts.length&&opts.every(p=>p[0]===allele&&p[1]===allele),allHave=opts.length&&opts.every(p=>p.includes(allele));let p=0;if(allHomo)p=Math.pow(.5,Math.max(0,depth-1));else if(allHave)p=Math.pow(.5,depth);else{const g=Base.normalizeGenetics(a.genetics).loci[locus].alleles;if(g[0]===allele&&g[1]===allele)p=Math.pow(.5,Math.max(0,depth-1));else if(g.includes(allele)&&!g.includes('_'))p=Math.pow(.5,depth);}if(p)paths.push({ancestorId:a.id,ancestorName:a.name,depth,probability:p,path:path.concat(a.id)});walk(a.sireId,depth+1,path.concat(a.id));walk(a.damId,depth+1,path.concat(a.id));}walk(animal?.sireId,1,[]);walk(animal?.damId,1,[]);const estimate=1-paths.reduce((prod,x)=>prod*(1-x.probability),1);return{estimate,paths};}
function siblingEvidence(animal,animals,locus,allele){const siblings=(animals||[]).filter(a=>a.id!==animal.id&&((animal.sireId&&a.sireId===animal.sireId)||(animal.damId&&a.damId===animal.damId)));const informative=siblings.filter(s=>phenotypePairs(s,locus).length&&phenotypePairs(s,locus).every(p=>p.includes(allele)));return informative.map(s=>({siblingId:s.id,siblingName:s.name,note:`${s.name||'A sibling'} provides family evidence for ${allele} at ${locus}; this is not direct proof that ${animal.name||'the selected rabbit'} inherited it.`}));}
function offspringEvidenceMateAware(parent,animals){const by=new Map((animals||[]).map(a=>[String(a.id),a])),children=(animals||[]).filter(c=>String(c.sireId||'')===String(parent.id)||String(c.damId||'')===String(parent.id)),out=[];for(const child of children){const mateId=String(child.sireId||'')===String(parent.id)?child.damId:child.sireId,mate=by.get(String(mateId||''));if(!mate)continue;for(const [l,a,label] of recessiveRequirement(child.color||child.variety)){if(canSupply(parent,l,a)&&canSupply(mate,l,a))out.push({locus:l,allele:a,status:'Proven by Offspring',childId:child.id,mateId:mate.id,note:`${child.name||'This offspring'} requires ${a}${a} for ${label}. With both recorded parents present, each parent had to supply one ${a} allele.`});}
    const cc=norm(child.color||child.variety);
    for(const [l,a,label] of [["E","ej","Japanese/Harlequin"],["C","cchd","Magpie/Chinchilla"]]){if((l==='E'&&/harlequin|magpie|tricolor/.test(cc))||(l==='C'&&/magpie/.test(cc))){const mateCan=canSupply(mate,l,a),parentCan=canSupply(parent,l,a);if(parentCan&&!mateCan)out.push({locus:l,allele:a,status:'Proven by Offspring',childId:child.id,mateId:mate.id,note:`${child.name||'This offspring'} requires ${a} for ${label}, and the recorded mate cannot supply ${a}; ${parent.name||'this parent'} therefore had to supply it.`});else if(parentCan&&mateCan)out.push({locus:l,allele:a,status:'Strongly Inferred',childId:child.id,mateId:mate.id,note:`${child.name||'This offspring'} supports ${a}, but either parent could have supplied it, so it is not treated as direct proof for ${parent.name||'this parent'}.`});}}
  }
  return out;
}
function childDistribution(scenario){let rows=[{genotype:{},probability:1}];for(const item of scenario){const cross=Base.crossLocus(item.locus,item.parent1,item.parent2).outcomes,next=[];for(const row of rows)for(const o of cross)next.push({genotype:{...row.genotype,[item.locus]:o.alleles},probability:row.probability*o.probability});rows=next;}const local=new Map();for(const row of rows){const ph=Base.phenotypeFromGenotype(row.genotype);if(!ph||ph.name==='Unknown')continue;const e=local.get(ph.name)||{name:ph.name,family:ph.family,probability:0,underlyingName:ph.underlyingName||ph.name};e.probability+=row.probability;local.set(ph.name,e);}return local;}
function enumerateScenarios(p1,p2,max=12000){const choices=DISPLAY.map(l=>{const a=phenotypePairs(p1,l),b=phenotypePairs(p2,l),out=[];for(const x of a)for(const y of b)out.push({locus:l,parent1:x,parent2:y});return out;}),total=choices.reduce((n,c)=>n*c.length,1);if(total>max)return{scenarios:[],total,truncated:true,choices};let scenarios=[[]];for(const locusChoices of choices){const next=[];for(const s of scenarios)for(const c of locusChoices)next.push(s.concat(c));scenarios=next;}return{scenarios,total,truncated:false,choices};}
function uncertaintyReason(name,p1,p2){const n=norm(name),needs=[];const check=(l,a,label)=>{const u=[];for(const p of [p1,p2]){const opts=phenotypePairs(p,l),has=opts.some(x=>x.includes(a)),all=opts.every(x=>x.includes(a));if(has&&!all)u.push(p.name||'one parent');}if(u.length)needs.push(`${u.join(' and ')} ${u.length>1?'have':'has'} unresolved ${label} (${a}) status`);};if(/chocolate|lilac/.test(n))check('B','b','chocolate-carrier');if(/blue|lilac|opal|squirrel|smoke pearl|cream/.test(n))check('D','d','dilute-carrier');if(/rew|red[- ]?eyed white/.test(n))check('C','c','REW-carrier');if(/bew|blue[- ]?eyed white/.test(n))check('V','v','Vienna-carrier');if(/harlequin|magpie|tricolor/.test(n))check('E','ej','Japanese');if(/magpie/.test(n))check('C','cchd','chinchilla');if(/broken|charlie/.test(n))check('En','En','broken');return needs.length?`Depends on ${needs.join('; ')}.`:'';}
function colorRanges(p1,p2){const enumed=enumerateScenarios(p1,p2),stats=new Map();if(enumed.truncated)return{outcomes:[],scenarioCount:enumed.total,truncated:true};let count=0;for(const scenario of enumed.scenarios){const local=childDistribution(scenario);count++;for(const [name,row] of local){let s=stats.get(name);if(!s){s={name,family:row.family,underlyingName:row.underlyingName,minPositive:Infinity,maxProbability:0,presentCount:0};stats.set(name,s);}s.presentCount++;s.minPositive=Math.min(s.minPositive,row.probability);s.maxProbability=Math.max(s.maxProbability,row.probability);}}
  const outcomes=[...stats.values()].map(s=>({name:s.name,family:s.family,underlyingName:s.underlyingName,minProbability:s.presentCount===count?s.minPositive:0,maxProbability:s.maxProbability,exact:s.presentCount===count&&Math.abs(s.minPositive-s.maxProbability)<1e-9,conditional:s.presentCount<count,reason:uncertaintyReason(s.name,p1,p2)})).sort((a,b)=>b.maxProbability-a.maxProbability||b.minProbability-a.minProbability||a.name.localeCompare(b.name));return{outcomes,scenarioCount:count,truncated:false};}
function exclusions(p1,p2){const out=[];const req=[['Chocolate family','B','b','Neither pairing can produce bb unless both parents can supply b.'],['Dilute family','D','d','Dilute colors require both parents to supply d.'],['REW','C','c','REW requires both parents to supply c.'],['BEW','V','v','BEW requires both parents to supply v.']];for(const [name,l,a,msg] of req)if(!canSupply(p1,l,a)||!canSupply(p2,l,a))out.push({name,locus:l,reason:msg});return out;}
function analyzePairing(p1,p2,ctx={}){const refined1=Base.refineAnimalGenetics?Base.refineAnimalGenetics(p1,ctx.animals||[],ctx.births||ctx.litters||[]).genetics:p1.genetics,refined2=Base.refineAnimalGenetics?Base.refineAnimalGenetics(p2,ctx.animals||[],ctx.births||ctx.litters||[]).genetics:p2.genetics,a={...p1,genetics:refined1},b={...p2,genetics:refined2};const ranges=colorRanges(a,b),conflicts=[...directConflict(a),...directConflict(b),...offspringConflicts(ctx.animals||[])],conditional=ranges.outcomes.filter(o=>o.conditional||o.minProbability!==o.maxProbability),predicted=ranges.outcomes.filter(o=>o.maxProbability>0),evidence={parent1:alleleEvidence(a),parent2:alleleEvidence(b),offspringParent1:offspringEvidenceMateAware(a,ctx.animals||[]),offspringParent2:offspringEvidenceMateAware(b,ctx.animals||[]),pedigree:{parent1:{B:ancestorCarrierEstimate(a,ctx.animals||[],'B','b'),D:ancestorCarrierEstimate(a,ctx.animals||[],'D','d'),C:ancestorCarrierEstimate(a,ctx.animals||[],'C','c'),V:ancestorCarrierEstimate(a,ctx.animals||[],'V','v')},parent2:{B:ancestorCarrierEstimate(b,ctx.animals||[],'B','b'),D:ancestorCarrierEstimate(b,ctx.animals||[],'D','d'),C:ancestorCarrierEstimate(b,ctx.animals||[],'C','c'),V:ancestorCarrierEstimate(b,ctx.animals||[],'V','v')}},siblings:{parent1:{B:siblingEvidence(a,ctx.animals||[],'B','b'),D:siblingEvidence(a,ctx.animals||[],'D','d'),C:siblingEvidence(a,ctx.animals||[],'C','c'),V:siblingEvidence(a,ctx.animals||[],'V','v')},parent2:{B:siblingEvidence(b,ctx.animals||[],'B','b'),D:siblingEvidence(b,ctx.animals||[],'D','d'),C:siblingEvidence(b,ctx.animals||[],'C','c'),V:siblingEvidence(b,ctx.animals||[],'V','v')}}};const legacy=Base.analyzePairing?Base.analyzePairing(a,b,ctx):{};return{...legacy,supported:true,releaseVersion:RELEASE_VERSION,engineVersion:ENGINE_VERSION,parent1:{id:a.id,name:a.name,color:a.color||a.variety||'',genotype:Base.genotypeText(a.genetics)},parent2:{id:b.id,name:b.name,color:b.color||b.variety||'',genotype:Base.genotypeText(b.genetics)},possibleOffspringColors:predicted,conditionalColors:conditional,currentlyExcluded:exclusions(a,b),geneticEvidence:evidence,contradictions:conflicts,scenarioCount:ranges.scenarioCount,scenarioTruncated:ranges.truncated,exact:predicted.length>0&&predicted.every(o=>o.exact),explanation:ranges.truncated?'The recorded genetics are too unconstrained to safely enumerate every phenotype combination on this device. Add phenotype, pedigree, carrier, or genotype evidence to narrow the result.':'Unknown alleles widen the calculated color ranges. They do not stop the calculation.',disclaimer:'HerdHarbor genetics predictions are breeding-planning estimates based on recorded information and deterministic inheritance rules. They are not DNA tests.'};}
return Object.freeze({...Base,VERSION:ENGINE_VERSION,RELEASE_VERSION,phenotypePairs,canSupply,directConflict,offspringConflicts,offspringEvidenceMateAware,ancestorCarrierEstimate,siblingEvidence,colorRanges,analyzePairing,rangeText});
});
