(() => {
"use strict";
const Core=window.HerdHarborBreedingIntelligenceCore;
if(!Core?.normalizeGenetics||!Core?.EDITABLE_LOCI)return;
const KEY="herdharbor_pre_alpha_v1";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
let modal=null,pendingDetail="";

const GROUP_LABELS=Object.freeze({"core-color":"Core Color","color-pattern":"Color & Pattern","color-modifier":"Color Modifiers",coat:"Coat & Fur","conformation-health":"Conformation & Health-Linked",conformation:"Conformation"});
const STATUS_OPTIONS=Object.freeze([["unknown","Unknown"],["possible","Possible"],["strongly-inferred","Strongly Inferred"],["confirmed","Confirmed"]]);
const SOURCE_OPTIONS=Object.freeze([["","Not recorded"],["breeder","Breeder confirmed"],["phenotype","Phenotype"],["pedigree","Pedigree"],["offspring","Offspring"],["genetic-test","DNA / genetic test"]]);

function read(){try{const state=JSON.parse(localStorage.getItem(KEY)||"{}");state.animals=Array.isArray(state.animals)?state.animals:[];state.births=Array.isArray(state.births)?state.births:[];state.litters=Array.isArray(state.litters)?state.litters:[];return state;}catch{return{animals:[],births:[],litters:[]};}}
async function persist(state){localStorage.setItem(KEY,JSON.stringify(state));try{await window.HerdHarborCloud?.syncNow?.();}catch(error){console.warn("Genetics saved locally; cloud sync can retry.",error);}}
const isRabbit=a=>String(Core.canonicalSpecies?.(a?.species)||a?.species||"").toLowerCase()==="rabbit";
const rabbits=state=>state.animals.filter(isRabbit);
const label=a=>`${a?.name||a?.tag||"Unnamed rabbit"}${a?.color||a?.variety?` — ${a.color||a.variety}`:""}`;
function options(list,id){return'<option value="">Select a rabbit…</option>'+list.map(a=>`<option value="${esc(a.id)}" ${String(a.id)===String(id||"")?"selected":""}>${esc(label(a))}</option>`).join("");}
function close(){modal?.remove?.();modal=null;}
function open(title,html){close();if(typeof document.createElement!=="function")return null;modal=document.createElement("div");modal.className="hh-bi-modal-backdrop";modal.innerHTML=`<section class="hh-bi-modal" role="dialog" aria-modal="true"><header><div><span class="hh-bi-kicker">HerdHarbor Alpha v${esc(window.HerdHarborBuild?.version||"1.6.5")} · Rabbit Genetics</span><h2>${esc(title)}</h2></div><button type="button" class="hh-bi-close" data-gv2-close aria-label="Close">×</button></header><div class="hh-bi-modal-body">${html}</div></section>`;const target=document.body||document.documentElement||document.head;target?.appendChild?.(modal);return modal;}

function alleleSelect(locus,index,record){const values=Core.LOCI[locus].dominance||[];return `<select data-a="${index}" aria-label="${esc(locus)} allele ${index+1}"><option value="_">Unknown (_)</option>${values.map(a=>`<option value="${esc(a)}" ${record.alleles[index]===a?"selected":""}>${esc(a)}</option>`).join("")}</select>`;}
function locusRow(locus,genetics){const def=Core.LOCI[locus],record=genetics.loci[locus],expression=Core.traitExpression?.(locus,record.alleles)||{state:"unknown",label:"Unknown"},probabilistic=def.predictionModel==="mendelian";return `<div class="hh-bi-locus" data-locus="${esc(locus)}"><div class="hh-bi-locus-title"><strong>${esc(locus)} — ${esc(def.name)}</strong><span>${esc(def.scientificStatus)} · ${esc(def.predictionModel)}</span></div><div class="hh-bi-alleles">${alleleSelect(locus,0,record)}${alleleSelect(locus,1,record)}</div><label>Evidence status<select data-status>${STATUS_OPTIONS.map(([v,n])=>`<option value="${v}" ${record.status===v?"selected":""}>${n}</option>`).join("")}</select></label><label>Evidence source<select data-source>${SOURCE_OPTIONS.map(([v,n])=>`<option value="${v}" ${record.source===v?"selected":""}>${n}</option>`).join("")}</select></label><label>Structured value<input data-value value="${esc(record.value||"")}" placeholder="Optional structured trait value"></label><label>Evidence note<input data-note value="${esc(record.note||"")}" placeholder="Why is this genotype or trait record known?"></label><small><strong>Current interpretation:</strong> ${esc(expression.label)}${probabilistic?"":" · No Mendelian percentage is generated for this trait."}</small></div>`;}
function groupHtml(group,genetics){const loci=Core.EDITABLE_LOCI.filter(locus=>Core.LOCI[locus].group===group);if(!loci.length)return"";return `<details class="hh-bi-advanced" open><summary>${esc(GROUP_LABELS[group]||group)}</summary><div class="hh-bi-loci">${loci.map(locus=>locusRow(locus,genetics)).join("")}</div></details>`;}
function profileModel(animal){if(!animal)return null;const genetics=Core.normalizeGenetics(animal.genetics),phenotype=Core.canonicalPhenotype(genetics,animal.color||animal.variety||genetics.phenotype.recorded,animal.breed||genetics.breedProfileId),traits=Core.evaluateTraits(genetics);return{animal,genetics,phenotype,traits};}
function carrierSummary(model){const rows=model.traits.traits.filter(t=>["carrier","visual","expressed","lethal-risk"].includes(t.state));if(!rows.length)return'<p>No expressed or carrier state is currently resolved beyond the core color loci.</p>';return `<ul>${rows.map(t=>`<li><strong>${esc(t.locus)}:</strong> ${esc(t.label)} <small>(${esc(t.scientificStatus)}; ${esc(t.predictionModel)})</small></li>`).join("")}</ul>`;}
function historyHtml(genetics){const evidence=(genetics.evidence||[]).slice().reverse().slice(0,15),conflicts=genetics.conflicts||[];return `<div class="hh-bi-evidence-panel"><h3>Genetic Evidence</h3>${evidence.length?`<ul>${evidence.map(x=>`<li><strong>${esc(x.locus||"Record")}</strong> — ${esc(x.source||x.status||"Unknown source")}${x.note?` · ${esc(x.note)}`:""}</li>`).join("")}</ul>`:'<p>No structured genetic evidence has been recorded yet.</p>'}</div>${conflicts.length?`<div class="hh-bi-warning"><strong>${conflicts.length} evidence conflict(s).</strong> Stronger evidence was retained for review instead of being silently overwritten.</div>`:""}`;}
function profile(id){const state=read(),list=rabbits(state),animal=list.find(x=>String(x.id)===String(id))||list[0];if(!animal)return open("Rabbit Genetics",'<div class="hh-bi-empty">Add a rabbit before creating a genetics profile.</div>');const model=profileModel(animal),g=model.genetics,p=model.phenotype,groups=["core-color","color-pattern","color-modifier","coat","conformation-health","conformation"];const html=`<div class="hh-bi-form-row"><label>Rabbit<select id="gv2-animal">${options(list,animal.id)}</select></label><label>Recorded phenotype<input value="${esc(animal.color||animal.variety||"")}" disabled></label></div><div class="hh-bi-profile-summary"><strong>${esc(label(animal))}</strong><span>Canonical phenotype: ${esc(p.canonical)} · ${esc(p.id)}</span><span>Breed terminology: ${esc(p.breedProfile.label)} → <strong>${esc(p.breedTerm)}</strong></span><span>Registry recognition: ${esc(p.registryRecognition.status)} — biological genetics are calculated separately.</span><span>Known genotype: ${esc(Core.genotypeText(g)||"Unknown")}</span></div><div class="hh-bi-two-col"><div><h3>Tracked expression & carriers</h3>${carrierSummary(model)}</div><div><h3>Lutino</h3><p><strong>${esc(Core.traitExpression("Lu",g.loci.Lu.alleles).label)}</strong></p><p class="hh-bi-note">Lutino is tracked as Visual / Carrier / Non-carrier / Unknown with its scientific status displayed. HerdHarbor does not hide uncertainty.</p></div></div>${groups.map(group=>groupHtml(group,g)).join("")}${historyHtml(g)}<div class="hh-bi-modal-actions"><button type="button" class="primary" id="gv2-save">Save Genetics</button></div><p class="hh-bi-save-confirmation" id="gv2-save-confirmation" role="status" aria-live="polite" hidden></p>`;const host=open("Rabbit Genetics",html);bindProfile(host,animal.id);return host;}
function editsFromModal(host){const loci={};host?.querySelectorAll?.("[data-locus]")?.forEach?.(row=>{const locus=row.dataset.locus;loci[locus]={alleles:[row.querySelector?.('[data-a="0"]')?.value||"_",row.querySelector?.('[data-a="1"]')?.value||"_"],status:row.querySelector?.("[data-status]")?.value||"unknown",source:row.querySelector?.("[data-source]")?.value||"",value:row.querySelector?.("[data-value]")?.value||"",note:row.querySelector?.("[data-note]")?.value||""};});return{loci};}
function applyProfileEditsToState(state,animalId,edits){const next=clone(state||{});next.animals=Array.isArray(next.animals)?next.animals:[];const animal=next.animals.find(a=>String(a.id)===String(animalId));if(!animal)return next;let genetics=Core.normalizeGenetics(animal.genetics);for(const locus of Core.EDITABLE_LOCI){const patch=edits?.loci?.[locus];if(!patch)continue;genetics=Core.updateLocusRecord(genetics,locus,patch,"breeder-profile-edit");}genetics.breedProfileId=Core.resolveBreedProfile(animal.breed).id;genetics.phenotype.recorded=animal.color||animal.variety||genetics.phenotype.recorded||"";const phenotype=Core.canonicalPhenotype(genetics,genetics.phenotype.recorded,animal.breed);genetics.phenotype.canonicalId=phenotype.id;genetics.phenotype.canonical=phenotype.canonical;genetics.phenotype.family=phenotype.family;genetics.phenotype.breedTerm=phenotype.breedTerm;animal.genetics=genetics;return next;}
async function saveProfileEdits(animalId,edits){const next=applyProfileEditsToState(read(),animalId,edits);await persist(next);return next;}
function bindProfile(host,animalId){if(!host?.querySelector)return;const select=host.querySelector("#gv2-animal");if(select)select.onchange=event=>profile(event.target.value);const button=host.querySelector("#gv2-save");if(!button)return;button.onclick=async()=>{const confirmation=host.querySelector("#gv2-save-confirmation");button.disabled=true;button.textContent="Saving…";try{await saveProfileEdits(animalId,editsFromModal(host));button.textContent="Saved";if(confirmation){confirmation.hidden=false;confirmation.textContent="Genetics saved.";}profile(animalId);}catch(error){console.error("Genetics profile could not be saved",error);button.disabled=false;button.textContent="Save Genetics";if(confirmation){confirmation.hidden=false;confirmation.textContent="Genetics could not be saved. Try again.";}}};}
function openPrediction(){return window.HerdHarborRabbitGeneticsV145?.openPrediction?.();}
function inject(){const state=read();document.querySelectorAll?.(".animal-card")?.forEach?.(card=>{const view=card.querySelector?.("[data-view-animal]");if(!view)return;const animal=state.animals.find(x=>String(x.id)===String(view.dataset.viewAnimal));if(!isRabbit(animal))return;const footer=card.querySelector?.(".animal-card-footer");if(footer&&!footer.querySelector?.("[data-gv2-profile]")){const button=document.createElement("button");button.type="button";button.className="button button-ghost button-small";button.textContent="Genetics";button.dataset.gv2Profile=animal.id;button.setAttribute?.("aria-label",`Open genetics for ${animal.name||animal.tag||"rabbit"}`);button.addEventListener?.("click",event=>{event.preventDefault?.();event.stopPropagation?.();profile(animal.id);});footer.appendChild?.(button);}});const content=document.querySelector?.("#modal-content"),back=document.querySelector?.("#modal-backdrop");if(pendingDetail&&content&&back&&!back.classList?.contains?.("hidden")&&!content.querySelector?.("#gv2-detail")){const animal=state.animals.find(x=>String(x.id)===String(pendingDetail));if(isRabbit(animal)){const model=profileModel(animal),section=document.createElement("section");section.id="gv2-detail";section.className="hh-bi-animal-genetics-panel";section.innerHTML=`<h3>Genetics <span class="hh-bi-badge">Optional</span></h3><p>Phenotype: <strong>${esc(animal.color||animal.variety||"Unknown")}</strong> · Canonical: <strong>${esc(model.phenotype.canonical)}</strong> · ${esc(model.phenotype.breedTerm)}</p><button type="button" class="button button-ghost" data-gv2-profile="${esc(animal.id)}">Open Genetics</button>`;content.appendChild?.(section);}}}
function onClick(event){const view=event.target?.closest?.("[data-view-animal]");if(view)pendingDetail=view.dataset.viewAnimal||"";const trigger=event.target?.closest?.("[data-gv2-profile]");if(trigger){event.preventDefault?.();event.stopImmediatePropagation?.();profile(trigger.dataset.gv2Profile);return;}if(event.target?.closest?.("[data-gv2-close]")||event.target===modal)close();}
function boot(){inject();if(typeof MutationObserver==="function"&&document.body){const observer=new MutationObserver(()=>inject());observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});window.__hhRabbitGeneticsV2Observer=observer;}}
if(typeof document.addEventListener==="function"){document.addEventListener("click",onClick,true);document.addEventListener("keydown",event=>{if(event.key==="Escape")close();});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();}
window.HerdHarborRabbitGeneticsV2=Object.freeze({version:"1.6.5",schemaVersion:Core.SCHEMA_VERSION,openProfile:profile,openPrediction,refresh:inject,profileModel,applyProfileEditsToState,saveProfileEdits});
})();
