(() => {
"use strict";
const Core=window.HerdHarborBreedingIntelligenceCore;
const Records=window.HerdHarborRabbitRecords;
if(!Core||!Records)return;
const KEY="herdharbor_pre_alpha_v1";
let modal=null,lastPrediction=null,saveInFlight=false;
const esc=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const clone=v=>Core.deepClone?Core.deepClone(v):JSON.parse(JSON.stringify(v));
const read=()=>{try{const s=JSON.parse(localStorage.getItem(KEY)||"{}");s.animals=Array.isArray(s.animals)?s.animals:[];s.litters=Array.isArray(s.litters)?s.litters:[];s.births=Array.isArray(s.births)?s.births:[];return s}catch{return{animals:[],litters:[],births:[]}}};
const pct=v=>`${Math.round(Number(v||0)*10000)/100}%`;
const range=o=>Math.abs(Number(o.maxProbability||0)-Number(o.minProbability||0))<1e-10?pct(o.minProbability):`${pct(o.minProbability)}–${pct(o.maxProbability)}`;
const label=a=>`${a?.name||a?.tag||a?.id||"Unnamed rabbit"}${a?.color||a?.variety?` — ${a.color||a.variety}`:""}`;
function options(list,id){return'<option value="">Select a rabbit…</option>'+list.map(a=>`<option value="${esc(a.id)}" ${String(a.id)===String(id||"")?"selected":""}>${esc(label(a))}</option>`).join("")}
function close(){modal?.remove();modal=null;lastPrediction=null;saveInFlight=false}
function open(title,html){close();modal=document.createElement("div");modal.className="hh-bi-modal-backdrop";modal.innerHTML=`<section class="hh-bi-modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><div><span class="hh-bi-kicker">HerdHarbor Alpha v${window.HerdHarborBuild?.version||"1.6.5"} · Rabbit Genetics</span><h2>${esc(title)}</h2></div><button type="button" class="hh-bi-close" data-v151-close aria-label="Close">×</button></header><div class="hh-bi-modal-body">${html}</div></section>`;const target=document.body||document.documentElement||document.head;if(!target)return;target.appendChild(modal)}
function colorRows(rows,conditionalOnly=false){if(!rows?.length)return'<p>No supported color outcome is available from the current evidence.</p>';return rows.map(o=>`<div class="hh-bi-result-row"><div><strong>${esc(o.name)}</strong><span>${esc(o.family||"Rabbit coat color")}</span>${o.reason?`<small>${esc(o.reason)}</small>`:""}${conditionalOnly?'<small>Carrier-dependent / unresolved genetics</small>':""}</div><b>${esc(range(o))}</b></div>`).join("")}
function evidenceRows(name,rows){return`<div><h3>${esc(name)}</h3>${rows?.length?`<div class="hh-bi-results">${rows.map(r=>`<div class="hh-bi-result-row"><div><strong>${esc(r.locus)} locus · ${esc(r.genotype)}</strong><span>${esc(r.status)}</span>${r.note?`<small>${esc(r.note)}</small>`:""}</div></div>`).join("")}</div>`:'<p>No genetics evidence recorded.</p>'}</div>`}
function pedigreeSummary(name,p){const rows=[];for(const [l,v] of Object.entries(p||{})){if(v?.estimate>0)rows.push(`<li><strong>${esc(l)} locus:</strong> family-evidence carrier estimate ${pct(v.estimate)}. ${v.paths.map(x=>`${esc(x.ancestorName||"ancestor")} (generation ${x.depth})`).join(" · ")}</li>`)}return`<div><h3>${esc(name)} pedigree evidence</h3>${rows.length?`<ul>${rows.join("")}</ul>`:'<p>No tracked recessive carrier evidence found in the recorded three-generation pedigree.</p>'}</div>`}
function familyEvidence(name,sibs,offspring){const siblingRows=[];for(const arr of Object.values(sibs||{}))for(const x of arr||[])siblingRows.push(`<li><strong>Sibling evidence:</strong> ${esc(x.note)}</li>`);const offspringRows=(offspring||[]).map(x=>`<li><strong>${esc(x.status)}:</strong> ${esc(x.note)}</li>`);return`<div><h3>${esc(name)} offspring & family evidence</h3>${offspringRows.length||siblingRows.length?`<ul>${offspringRows.join("")}${siblingRows.join("")}</ul>`:'<p>No informative offspring or sibling evidence is currently recorded.</p>'}</div>`}
function conflictHtml(items){return items?.length?`<div class="hh-bi-warning"><strong>Genetic conflict detected.</strong><ul>${items.slice(0,8).map(x=>`<li>${esc(x.message)}</li>`).join("")}</ul><p>HerdHarbor did not silently alter the breeder-entered record. Review the conflicting color, genotype, or parentage before relying on this prediction.</p></div>`:""}
function geneticsAtPrediction(animal,state){try{return clone(Core.refineAnimalGenetics(animal,state.animals||[],state.births||state.litters||[]).genetics)}catch{return clone(Core.normalizeGenetics(animal.genetics))}}
function makePredictionDraft(analysis,buck,doe,state){return{analysis:clone(analysis),generatedAt:new Date().toISOString(),buck:{id:buck.id,name:buck.name||buck.tag||"Buck",color:buck.color||buck.variety||"",genetics:geneticsAtPrediction(buck,state)},doe:{id:doe.id,name:doe.name||doe.tag||"Doe",color:doe.color||doe.variety||"",genetics:geneticsAtPrediction(doe,state)}}}
async function saveCurrentPrediction(button){if(saveInFlight||button.disabled||!lastPrediction)return;const confirmation=modal?.querySelector("#v151-save-confirmation"),api=window.HerdHarborBreedingIntelligence;if(!api?.savePredictionSnapshot){if(confirmation){confirmation.hidden=false;confirmation.textContent="Prediction history is unavailable. Please reopen Breeding Intelligence and try again.";confirmation.classList.add("error")}return}saveInFlight=true;button.disabled=true;button.textContent="Saving…";try{await api.savePredictionSnapshot(lastPrediction);button.textContent="Prediction Saved";if(confirmation){confirmation.hidden=false;confirmation.textContent="Prediction saved to history.";confirmation.classList.remove("error")}lastPrediction=null}catch(error){console.error("Prediction snapshot could not be saved:",error);button.disabled=false;button.textContent="Save Prediction Snapshot";if(confirmation){confirmation.hidden=false;confirmation.textContent="Prediction could not be saved. Try again.";confirmation.classList.add("error")}}finally{saveInFlight=false}}
function pair(buckId="",doeId="",run=false){const s=read(),all=s.animals||[],bucks=Records.rabbitsForSex(all,"Male"),does=Records.rabbitsForSex(all,"Female"),buck=bucks.find(a=>String(a.id)===String(buckId)),doe=does.find(a=>String(a.id)===String(doeId));let draft=null,body=`<div class="hh-bi-pair-selectors"><label>Buck<select id="v151-buck">${options(bucks,buck?.id)}</select></label><label>Doe<select id="v151-doe">${options(does,doe?.id)}</select></label><button type="button" class="primary" id="v151-run">View Genetics Prediction</button></div><p class="hh-bi-note">Buck and Doe lists use the rabbit's stored sex with exact Male/Female matching. Only current Active/Breeding rabbits are offered.</p>`;
if(run&&buck&&doe){const a=Core.analyzePairing(buck,doe,s);const allColors=a.possibleOffspringColors||[],conditional=(a.conditionalColors||[]).filter(o=>Number(o.maxProbability)>0),knownTechnical=[...(a.geneticEvidence?.parent1||[]),...(a.geneticEvidence?.parent2||[])];if(a?.supported)draft=makePredictionDraft(a,buck,doe,s);body+=`${conflictHtml(a.contradictions)}${a.scenarioTruncated?'<div class="hh-bi-warning"><strong>Genetics need more evidence.</strong> This pairing has more unresolved genotype combinations than HerdHarbor can safely enumerate on-device. Add known phenotype/genotype/carrier or pedigree information to narrow it; no fake percentages were generated.</div>':""}
<div class="hh-bi-analysis-header"><div><span class="hh-bi-kicker">A · Possible Offspring Colors</span><h3>Breeder-readable coat color predictions</h3></div><span class="hh-bi-confidence ${a.exact?"exact":"conditional"}">${a.exact?"Deterministic percentages":"Genetic probability ranges"}</span></div><div class="hh-bi-results">${colorRows(allColors)}</div>
<div class="hh-bi-evidence-panel"><h3>B · Conditional / Carrier-Dependent Colors</h3>${conditional.length?`<div class="hh-bi-results">${colorRows(conditional,true)}</div>`:'<p>No currently predicted coat color depends on an unresolved tracked carrier allele.</p>'}</div>
<div class="hh-bi-evidence-panel"><h3>C · Genetics & Carrier Information</h3><div class="hh-bi-profile-summary"><strong>${esc(doe.name||"Doe")}</strong><span>${esc(a.parent2?.genotype||Core.genotypeText(doe.genetics))}</span><strong>${esc(buck.name||"Buck")}</strong><span>${esc(a.parent1?.genotype||Core.genotypeText(buck.genetics))}</span><em>Evidence status describes why an allele is believed; it is not a DNA claim unless a genetic test is actually recorded.</em></div><div class="hh-bi-two-col">${evidenceRows(buck.name||"Buck",a.geneticEvidence?.parent1)}${evidenceRows(doe.name||"Doe",a.geneticEvidence?.parent2)}</div><div class="hh-bi-two-col">${pedigreeSummary(buck.name||"Buck",a.geneticEvidence?.pedigree?.parent1)}${pedigreeSummary(doe.name||"Doe",a.geneticEvidence?.pedigree?.parent2)}</div><div class="hh-bi-two-col">${familyEvidence(buck.name||"Buck",a.geneticEvidence?.siblings?.parent1,a.geneticEvidence?.offspringParent1)}${familyEvidence(doe.name||"Doe",a.geneticEvidence?.siblings?.parent2,a.geneticEvidence?.offspringParent2)}</div></div>
<div class="hh-bi-evidence-panel"><h3>D · Currently Excluded</h3>${a.currentlyExcluded?.length?`<ul>${a.currentlyExcluded.map(x=>`<li><strong>${esc(x.name)} — Excluded.</strong> ${esc(x.reason)}</li>`).join("")}</ul>`:'<p>No tracked color family can be conclusively excluded with the current records.</p>'}</div>
<div class="hh-bi-explain"><h3>How HerdHarbor calculated this</h3><p>${esc(a.explanation||"Unknown alleles widen the result instead of stopping calculation.")}</p><p>${esc(a.disclaimer||"Predictions are breeding-planning estimates, not DNA tests.")}</p><p><strong>Genotype probability and visible expression are separate:</strong> Vv does not predict how much Vienna marking will show, and modifier intensity such as rufus is not assigned fake precision.</p></div>${draft?'<div class="hh-bi-modal-actions"><button type="button" class="primary" id="v151-save-prediction">Save Prediction Snapshot</button></div><p class="hh-bi-save-confirmation" id="v151-save-confirmation" role="status" aria-live="polite" hidden></p>':""}` }else if(run)body+='<div class="hh-bi-warning">Choose one Male buck and one Female doe.</div>';else body+='<div class="hh-bi-empty">Select the buck and doe, then open the optional genetics prediction.</div>';
open("Rabbit Genetics Prediction",body);lastPrediction=draft;saveInFlight=false;modal.querySelector("#v151-run")?.addEventListener("click",()=>pair(modal.querySelector("#v151-buck").value,modal.querySelector("#v151-doe").value,true));modal.querySelector("#v151-save-prediction")?.addEventListener("click",event=>saveCurrentPrediction(event.currentTarget));}
document.addEventListener("click",event=>{const trigger=event.target.closest('[data-bi-action="pair"]');if(trigger){event.preventDefault();event.stopImmediatePropagation();pair();return}if(event.target.closest("[data-v151-close]")||event.target===modal)close()},true);
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&modal)close()});
window.HerdHarborRabbitGeneticsV145=Object.freeze({version:"1.6.1",openPrediction:pair,normalizeSex:Records.normalizeSex});
})();
