(() => {
"use strict";
const Core=window.HerdHarborBreedingIntelligenceCore;
if(!Core?.normalizeGenetics||!Core?.EDITABLE_LOCI)return;
const KEY="herdharbor_pre_alpha_v1";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const pct=v=>`${Math.round(Number(v||0)*10000)/100}%`;
let modal=null,pendingDetail="",saveInFlight=false,lastPrediction=null;

const GROUP_LABELS=Object.freeze({"core-color":"Core Color","color-pattern":"Color & Pattern","color-modifier":"Color Modifiers",coat:"Coat & Fur","conformation-health":"Conformation & Health-Linked",conformation:"Conformation"});
const STATUS_OPTIONS=Object.freeze([["unknown","Unknown"],["possible","Possible"],["strongly-inferred","Strongly Inferred"],["confirmed","Confirmed"]]);
const SOURCE_OPTIONS=Object.freeze([["","Not recorded"],["breeder","Breeder confirmed"],["phenotype","Phenotype"],["pedigree","Pedigree"],["offspring","Offspring"],["genetic-test","DNA / genetic test"]]);

function read(){try{const state=JSON.parse(localStorage.getItem(KEY)||"{}");state.animals=Array.isArray(state.animals)?state.animals:[];state.births=Array.isArray(state.births)?state.births:[];state.litters=Array.isArray(state.litters)?state.litters:[];return state;}catch{return{animals:[],births:[],litters:[]};}}
async function persist(state){localStorage.setItem(KEY,JSON.stringify(state));try{await window.HerdHarborCloud?.syncNow?.();}catch(error){console.warn("Genetics saved locally; cloud sync can retry.",error);}}
const isRabbit=a=>String(Core.canonicalSpecies?.(a?.species)||a?.species||"").toLowerCase()==="rabbit";
const rabbits=state=>state.animals.filter(isRabbit);
const active=a=>!a?.status||["active","breeding"].includes(String(a.status).toLowerCase());
const sexIs=(a,wanted)=>wanted==="male"?/^(male|buck)$/i.test(String(a?.sex||"").trim()):/^(female|doe)$/i.test(String(a?.sex||"").trim());
const label=a=>`${a?.name||a?.tag||"Unnamed rabbit"}${a?.color||a?.variety?` — ${a.color||a.variety}`:""}`;
function options(list,id){return'<option value="">Select a rabbit…</option>'+list.map(a=>`<option value="${esc(a.id)}" ${String(a.id)===String(id||"")?"selected":""}>${esc(label(a))}</option>`).join("");}
function close(){modal?.remove?.();modal=null;lastPrediction=null;saveInFlight=false;}
function open(title,html){close();if(typeof document.createElement!=="function")return null;modal=document.createElement("div");modal.className="hh-bi-modal-backdrop";modal.innerHTML=`<section class="hh-bi-modal" role="dialog" aria-modal="true"><header><div><span class="hh-bi-kicker">HerdHarbor Alpha v${esc(window.HerdHarborBuild?.version||"1.6.5")} · Rabbit Genetics</span><h2>${esc(title)}</h2></div><button type="button" class="hh-bi-close" data-gv2-close aria-label="Close">×</button></header><div class="hh-bi-modal-body">${html}</div></section>`;const target=document.body||document.documentElement||document.head;target?.appendChild?.(modal);return modal;}

function alleleSelect(locus,index,record){const values=Core.LOCI[locus].dominance||[];return `<select data-a="${index}" aria-label="${esc(locus)} allele ${index+1}"><option value="_">Unknown (_)</option>${values.map(a=>`<option value="${esc(a)}" ${record.alleles[index]===a?"selected":""}>${esc(a)}</option>`).join("")}</select>`;}
function locusRow(locus,genetics){const def=Core.LOCI[locus],record=genetics.loci[locus],expression=Core.traitExpression?.(locus,record.alleles)||{state:"unknown",label:"Unknown"},probabilistic=def.predictionModel==="mendelian";return `<div class="hh-bi-locus" data-locus="${esc(locus)}"><div class="hh-bi-locus-title"><strong>${esc(locus)} — ${esc(def.name)}</strong><span>${esc(def.scientificStatus)} · ${esc(def.predictionModel)}</span></div><div class="hh-bi-alleles">${alleleSelect(locus,0,record)}${alleleSelect(locus,1,record)}</div><label>Evidence status<select data-status>${STATUS_OPTIONS.map(([v,n])=>`<option value="${v}" ${record.status===v?"selected":""}>${n}</option>`).join("")}</select></label><label>Evidence source<select data-source>${SOURCE_OPTIONS.map(([v,n])=>`<option value="${v}" ${record.source===v?"selected":""}>${n}</option>`).join("")}</select></label><label>Structured value<input data-value value="${esc(record.value||"")}" placeholder="Optional structured trait value"></label><label>Evidence note<input data-note value="${esc(record.note||"")}" placeholder="Why is this genotype or trait record known?"></label><small><strong>Current interpretation:</strong> ${esc(expression.label)}${probabilistic?"":" · No Mendelian percentage is generated for this trait."}</small></div>`;}
function groupHtml(group,genetics){const loci=Core.EDITABLE_LOCI.filter(locus=>Core.LOCI[locus].group===group);if(!loci.length)return"";return `<details class="hh-bi-advanced" open><summary>${esc(GROUP_LABELS[group]||group)}</summary><div class="hh-bi-loci">${loci.map(locus=>locusRow(locus,genetics)).join("")}</div></details>`;}
function profileModel(animal){if(!animal)return null;const genetics=Core.normalizeGenetics(animal.genetics),phenotype=Core.canonicalPhenotype(genetics,animal.color||animal.variety||genetics.phenotype.recorded,animal.breed||genetics.breedProfileId),traits=Core.evaluateTraits(genetics);return{animal,genetics,phenotype,traits};}
function carrierSummary(model){const rows=model.traits.traits.filter(t=>["carrier","visual","expressed","lethal-risk"].includes(t.state));if(!rows.length)return'<p>No expressed or carrier state is currently resolved beyond the core color loci.</p>';return `<ul>${rows.map(t=>`<li><strong>${esc(t.locus)}:</strong> ${esc(t.label)} <small>(${esc(t.scientificStatus)}; ${esc(t.predictionModel)})</small></li>`).join("")}</ul>`;}
function historyHtml(genetics){const evidence=(genetics.evidence||[]).slice().reverse().slice(0,15),conflicts=genetics.conflicts||[];return `<div class="hh-bi-evidence-panel"><h3>Genetic Evidence</h3>${evidence.length?`<ul>${evidence.map(x=>`<li><strong>${esc(x.locus||"Record")}</strong> — ${esc(x.source||x.status||"Unknown source")}${x.note?` · ${esc(x.note)}`:""}</li>`).join("")}</ul>`:'<p>No structured genetic evidence has been recorded yet.</p>'}</div>${conflicts.length?`<div class="hh-bi-warning"><strong>${conflicts.length} evidence conflict(s).</strong> Stronger evidence was retained for review instead of being silently overwritten.</div>`:""}`;}
function profile(id){const state=read(),list=rabbits(state),animal=list.find(x=>String(x.id)===String(id))||list[0];if(!animal)return open("Rabbit Genetics",'<div class="hh-bi-empty">Add a rabbit before creating a genetics profile.</div>');const model=profileModel(animal),g=model.genetics,p=model.phenotype,groups=["core-color","color-pattern","color-modifier","coat","conformation-health","conformation"];const html=`<div class="hh-bi-form-row"><label>Rabbit<select id="gv2-animal">${options(list,animal.id)}</select></label><label>Recorded phenotype<input value="${esc(animal.color||animal.variety||"")}" disabled></label></div><div class="hh-bi-profile-summary"><strong>${esc(label(animal))}</strong><span>Canonical phenotype: ${esc(p.canonical)} · ${esc(p.id)}</span><span>Breed terminology: ${esc(p.breedProfile.label)} → <strong>${esc(p.breedTerm)}</strong></span><span>Registry recognition: ${esc(p.registryRecognition.status)} — biological genetics are calculated separately.</span><span>Known genotype: ${esc(Core.genotypeText(g)||"Unknown")}</span></div><div class="hh-bi-two-col"><div><h3>Tracked expression & carriers</h3>${carrierSummary(model)}</div><div><h3>Lutino</h3><p><strong>${esc(Core.traitExpression("Lu",g.loci.Lu.alleles).label)}</strong></p><p class="hh-bi-note">Lutino is tracked as Visual / Carrier / Non-carrier / Unknown with its scientific status displayed. HerdHarbor does not hide uncertainty.</p></div></div>${groups.map(group=>groupHtml(group,g)).join("")}${historyHtml(g)}<div class="hh-bi-modal-actions"><button type="button" class="button" id="gv2-open-pair">Open Pair Analysis</button><button type="button" class="primary" id="gv2-save">Save Genetics</button></div><p class="hh-bi-save-confirmation" id="gv2-save-confirmation" role="status" aria-live="polite" hidden></p>`;const host=open("Rabbit Genetics",html);bindProfile(host,animal.id);return host;}
function editsFromModal(host){const loci={};host?.querySelectorAll?.("[data-locus]")?.forEach?.(row=>{const locus=row.dataset.locus;loci[locus]={alleles:[row.querySelector?.('[data-a="0"]')?.value||"_",row.querySelector?.('[data-a="1"]')?.value||"_"],status:row.querySelector?.("[data-status]")?.value||"unknown",source:row.querySelector?.("[data-source]")?.value||"",value:row.querySelector?.("[data-value]")?.value||"",note:row.querySelector?.("[data-note]")?.value||""};});return{loci};}
function applyProfileEditsToState(state,animalId,edits){const next=clone(state||{});next.animals=Array.isArray(next.animals)?next.animals:[];const animal=next.animals.find(a=>String(a.id)===String(animalId));if(!animal)return next;let genetics=Core.normalizeGenetics(animal.genetics);for(const locus of Core.EDITABLE_LOCI){const patch=edits?.loci?.[locus];if(!patch)continue;genetics=Core.updateLocusRecord(genetics,locus,patch,"breeder-profile-edit");}genetics.breedProfileId=Core.resolveBreedProfile(animal.breed).id;genetics.phenotype.recorded=animal.color||animal.variety||genetics.phenotype.recorded||"";const phenotype=Core.canonicalPhenotype(genetics,genetics.phenotype.recorded,animal.breed);genetics.phenotype.canonicalId=phenotype.id;genetics.phenotype.canonical=phenotype.canonical;genetics.phenotype.family=phenotype.family;genetics.phenotype.breedTerm=phenotype.breedTerm;animal.genetics=genetics;return next;}
async function saveProfileEdits(animalId,edits){const next=applyProfileEditsToState(read(),animalId,edits);await persist(next);return next;}
function bindProfile(host,animalId){if(!host?.querySelector)return;const select=host.querySelector("#gv2-animal");if(select)select.onchange=event=>profile(event.target.value);host.querySelector("#gv2-open-pair")?.addEventListener?.("click",()=>pair());const button=host.querySelector("#gv2-save");if(!button)return;button.onclick=async()=>{const confirmation=host.querySelector("#gv2-save-confirmation");button.disabled=true;button.textContent="Saving…";try{await saveProfileEdits(animalId,editsFromModal(host));button.textContent="Saved";if(confirmation){confirmation.hidden=false;confirmation.textContent="Genetics saved.";}profile(animalId);}catch(error){console.error("Genetics profile could not be saved",error);button.disabled=false;button.textContent="Save Genetics";if(confirmation){confirmation.hidden=false;confirmation.textContent="Genetics could not be saved. Try again.";}}};}

function probabilityRange(row){const min=Number(row?.minProbability??row?.probability??0),max=Number(row?.maxProbability??row?.probability??0);return Math.abs(min-max)<1e-10?pct(min):`${pct(min)}–${pct(max)}`;}
function colorRows(analysis){const rows=analysis?.possibleOffspringColors||analysis?.exactOutcomes||analysis?.possibleOutcomes||[];if(!rows.length)return'<p>No supported named color outcome is available from the current evidence.</p>';return `<div class="hh-bi-results">${rows.map(row=>`<div class="hh-bi-result-row"><div><strong>${esc(row.name)}</strong><span>${esc(row.family||"Rabbit coat color")}</span>${row.reason?`<small>${esc(row.reason)}</small>`:""}</div><b>${row.probability!=null||row.minProbability!=null?esc(probabilityRange(row)):"Possible"}</b></div>`).join("")}</div>`;}
function parentRecordText(record){if(!record)return"Unknown";const genotype=Array.isArray(record.alleles)&&record.alleles.some(a=>a&&a!=="_")?record.alleles.join("/"):"Unknown genotype",value=record.value!==undefined&&record.value!==""?` · ${record.value}`:"";return `${genotype}${value}`;}
function extendedLocusRows(analysis){const rows=Object.values(analysis?.locusAnalyses||{}).filter(row=>!Core.CORE_LOCI.includes(row.locus));if(!rows.length)return'<p>No extended-locus analysis is available.</p>';return rows.map(row=>{if(row.probabilities===false)return `<details class="hh-bi-trait-result" open><summary><strong>${esc(row.locus)} · ${esc(row.name)}</strong><span>No Mendelian percentage</span></summary><p><strong>${esc(row.scientificStatus)}</strong> · ${esc(row.predictionModel)}</p><p>${esc(row.notice||"This trait is recorded without unsupported Mendelian percentages.")}</p><p>Parent records: ${esc(parentRecordText(row.parentRecords?.[0]))} × ${esc(parentRecordText(row.parentRecords?.[1]))}</p></details>`;if(row.exact)return `<details class="hh-bi-trait-result" open><summary><strong>${esc(row.locus)} · ${esc(row.name)}</strong><span>Calculated</span></summary><p><strong>${esc(row.scientificStatus)}</strong> · Mendelian</p>${(row.outcomes||[]).map(outcome=>`<div class="hh-bi-result-row"><div><strong>${esc(outcome.expression?.label||outcome.alleles?.join("/")||"Outcome")}</strong><span>${esc(outcome.alleles?.join("/")||"")}</span></div><b>${pct(outcome.probability)}</b></div>`).join("")}${row.caveat?`<p class="hh-bi-note">${esc(row.caveat)}</p>`:""}</details>`;return `<details class="hh-bi-trait-result"><summary><strong>${esc(row.locus)} · ${esc(row.name)}</strong><span>Unresolved</span></summary><p><strong>${esc(row.scientificStatus)}</strong> · Mendelian inheritance, but the recorded parental genotype is incomplete. No allele was guessed.</p></details>`;}).join("");}
function healthRows(analysis){const rows=analysis?.healthNotices||[];if(!rows.length)return"";return `<div class="hh-bi-warning"><h3>Breeding-health notices</h3><ul>${rows.map(row=>`<li><strong>${esc(row.locus||"Genetics")}${row.probability!=null?` · ${pct(row.probability)}`:""}:</strong> ${esc(row.message)}</li>`).join("")}</ul><p>These are informational breeding notices, not veterinary diagnoses.</p></div>`;}
function evidenceSummary(analysis){const evidence=analysis?.geneticEvidence;if(!evidence)return"";const rows=[...(evidence.parent1||[]),...(evidence.parent2||[])].filter(row=>row.status!=="Unknown");return `<div class="hh-bi-evidence-panel"><h3>Evidence used</h3>${rows.length?`<ul>${rows.slice(0,20).map(row=>`<li><strong>${esc(row.locus)}:</strong> ${esc(row.genotype)} · ${esc(row.status)}</li>`).join("")}</ul>`:'<p>No additional structured evidence was needed beyond the current records.</p>'}</div>`;}
function predictionDraft(analysis,buck,doe,state){const snapshot=animal=>{try{return clone(Core.refineAnimalGenetics?.(animal,state.animals||[],state.births||state.litters||[])?.genetics||Core.normalizeGenetics(animal.genetics));}catch{return clone(Core.normalizeGenetics(animal.genetics));}};return{analysis:clone(analysis),generatedAt:new Date().toISOString(),buck:{id:buck.id,name:buck.name||buck.tag||"Buck",color:buck.color||buck.variety||"",genetics:snapshot(buck)},doe:{id:doe.id,name:doe.name||doe.tag||"Doe",color:doe.color||doe.variety||"",genetics:snapshot(doe)}};}
async function savePrediction(button){if(saveInFlight||button?.disabled||!lastPrediction)return;const confirmation=modal?.querySelector?.("#gv2-pair-save-confirmation"),api=window.HerdHarborBreedingIntelligence;if(!api?.savePredictionSnapshot){if(confirmation){confirmation.hidden=false;confirmation.textContent="Prediction history is unavailable. Please reopen Breeding Intelligence and try again.";}return;}saveInFlight=true;button.disabled=true;button.textContent="Saving…";try{await api.savePredictionSnapshot(lastPrediction);button.textContent="Prediction Saved";if(confirmation){confirmation.hidden=false;confirmation.textContent="Prediction saved to history.";}lastPrediction=null;}catch(error){console.error("Prediction snapshot could not be saved",error);button.disabled=false;button.textContent="Save Prediction Snapshot";if(confirmation){confirmation.hidden=false;confirmation.textContent="Prediction could not be saved. Try again.";}}finally{saveInFlight=false;}}
function pair(buckId="",doeId="",run=false){const state=read(),list=rabbits(state).filter(active),bucks=list.filter(a=>sexIs(a,"male")),does=list.filter(a=>sexIs(a,"female")),buck=bucks.find(a=>String(a.id)===String(buckId)),doe=does.find(a=>String(a.id)===String(doeId));let body=`<div class="hh-bi-pair-selectors"><label>Buck<select id="gv2-buck">${options(bucks,buck?.id)}</select></label><label>Doe<select id="gv2-doe">${options(does,doe?.id)}</select></label><button type="button" class="primary" id="gv2-run">View Genetics Prediction</button></div><p class="hh-bi-note">Unknown alleles stay unknown. Mendelian loci may show probabilities; complex, polygenic, variable-expression, and informational traits never receive fabricated percentages.</p>`;lastPrediction=null;if(run&&buck&&doe){const analysis=Core.analyzePairing(buck,doe,state);if(analysis?.supported){lastPrediction=predictionDraft(analysis,buck,doe,state);body+=`<div class="hh-bi-analysis-header"><div><span class="hh-bi-kicker">Possible Offspring</span><h3>Color + complete tracked-locus analysis</h3></div><span class="hh-bi-confidence ${analysis.exact?"exact":"conditional"}">${analysis.exact?"Deterministic core-color probabilities":"Uncertainty preserved"}</span></div>${colorRows(analysis)}<div class="hh-bi-evidence-panel"><h3>Extended loci</h3>${extendedLocusRows(analysis)}</div>${healthRows(analysis)}${evidenceSummary(analysis)}<div class="hh-bi-explain"><h3>Why these results?</h3><p>${esc(analysis.explanation||"Recorded genetics and phenotype constraints were evaluated without inventing missing alleles.")}</p><p>${esc(analysis.disclaimer||"Genetic possibility is separate from registry recognition.")}</p></div><div class="hh-bi-modal-actions"><button type="button" class="primary" id="gv2-save-prediction">Save Prediction Snapshot</button></div><p class="hh-bi-save-confirmation" id="gv2-pair-save-confirmation" role="status" aria-live="polite" hidden></p>`;}else body+='<div class="hh-bi-warning">This pairing is not supported by the current Rabbit genetics engine.</div>';}else if(run)body+='<div class="hh-bi-warning">Choose one active buck and one active doe.</div>';else body+='<div class="hh-bi-empty">Choose a buck and doe to run Pair Analysis.</div>';const host=open("Rabbit Genetics Pair Analysis",body);if(host?.querySelector){host.querySelector("#gv2-run")?.addEventListener?.("click",()=>pair(host.querySelector("#gv2-buck")?.value||"",host.querySelector("#gv2-doe")?.value||"",true));host.querySelector("#gv2-save-prediction")?.addEventListener?.("click",event=>savePrediction(event.currentTarget));}return host;}

function inject(){const state=read();document.querySelectorAll?.(".animal-card")?.forEach?.(card=>{const view=card.querySelector?.("[data-view-animal]");if(!view)return;const animal=state.animals.find(x=>String(x.id)===String(view.dataset.viewAnimal));if(!isRabbit(animal))return;const footer=card.querySelector?.(".animal-card-footer");if(footer&&!footer.querySelector?.("[data-gv2-profile]")){const button=document.createElement("button");button.type="button";button.className="button button-ghost button-small";button.textContent="Genetics";button.dataset.gv2Profile=animal.id;button.setAttribute?.("aria-label",`Open genetics for ${animal.name||animal.tag||"rabbit"}`);button.addEventListener?.("click",event=>{event.preventDefault?.();event.stopPropagation?.();profile(animal.id);});footer.appendChild?.(button);}});const content=document.querySelector?.("#modal-content"),back=document.querySelector?.("#modal-backdrop");if(pendingDetail&&content&&back&&!back.classList?.contains?.("hidden")&&!content.querySelector?.("#gv2-detail")){const animal=state.animals.find(x=>String(x.id)===String(pendingDetail));if(isRabbit(animal)){const model=profileModel(animal),section=document.createElement("section");section.id="gv2-detail";section.className="hh-bi-animal-genetics-panel";section.innerHTML=`<h3>Genetics <span class="hh-bi-badge">Optional</span></h3><p>Phenotype: <strong>${esc(animal.color||animal.variety||"Unknown")}</strong> · Canonical: <strong>${esc(model.phenotype.canonical)}</strong> · ${esc(model.phenotype.breedTerm)}</p><button type="button" class="button button-ghost" data-gv2-profile="${esc(animal.id)}">Open Genetics</button>`;content.appendChild?.(section);}}}
function onDocumentClick(event){const view=event.target?.closest?.("[data-view-animal]");if(view)pendingDetail=view.dataset.viewAnimal||"";const trigger=event.target?.closest?.("[data-gv2-profile]");if(trigger){event.preventDefault?.();event.stopImmediatePropagation?.();profile(trigger.dataset.gv2Profile);return;}if(event.target?.closest?.("[data-gv2-close]")||event.target===modal)close();}
function onWindowCapture(event){const pairTrigger=event.target?.closest?.('[data-bi-action="pair"]');if(pairTrigger){event.preventDefault?.();event.stopImmediatePropagation?.();pair();return;}const profileTrigger=event.target?.closest?.('[data-bi-action="profile"]');if(profileTrigger){event.preventDefault?.();event.stopImmediatePropagation?.();profile(profileTrigger.dataset?.animalId||"");}}
function bridgeBreedingIntelligence(){const existing=window.HerdHarborBreedingIntelligence;if(!existing||existing.geneticsContractVersion===Core.GENETICS_CONTRACT_VERSION)return;window.HerdHarborBreedingIntelligence=Object.freeze({...existing,geneticsContractVersion:Core.GENETICS_CONTRACT_VERSION,openPairAnalysis:()=>pair(),openGeneticProfile:animalId=>profile(animalId||"")});}
function boot(){bridgeBreedingIntelligence();inject();if(typeof MutationObserver==="function"&&document.body){const observer=new MutationObserver(()=>{bridgeBreedingIntelligence();inject();});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});window.__hhRabbitGeneticsV2Observer=observer;}}
if(typeof window.addEventListener==="function")window.addEventListener("click",onWindowCapture,true);
if(typeof document.addEventListener==="function"){document.addEventListener("click",onDocumentClick,true);document.addEventListener("keydown",event=>{if(event.key==="Escape")close();});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();}
window.HerdHarborRabbitGeneticsV2=Object.freeze({version:"1.6.5",schemaVersion:Core.SCHEMA_VERSION,openProfile:profile,openPrediction:pair,refresh:inject,profileModel,applyProfileEditsToState,saveProfileEdits});
})();
