(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.HerdHarborStandards=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='1.6.1';
const STATUS=Object.freeze({RECOGNIZED:'recognized',WORKING:'working',PROPOSED:'proposed',DEVELOPING:'developing'});
const registries=new Map(),standards=[];
const clean=v=>String(v==null?'':v).trim();
const key=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const clone=v=>JSON.parse(JSON.stringify(v));
function registerOrganization(value){if(!value?.id||!value?.species)throw new Error('Standards organizations require an id and species.');const row=Object.freeze({...clone(value),id:key(value.id),species:key(value.species),optional:true});registries.set(row.id,row);return row;}
function registerStandard(value){const row=clone(value||{});if(!registries.has(key(row.registry)))throw new Error('Register the standards organization first.');for(const field of ['edition','breedId','breedName','species'])if(!clean(row[field]))throw new Error(`Standard ${field} is required.`);row.id=row.id||`${key(row.registry)}:${key(row.edition)}:${key(row.breedId)}`;row.registry=key(row.registry);row.species=key(row.species);row.breedId=key(row.breedId);row.status=row.status||STATUS.RECOGNIZED;row.licensing={contentMode:'structured-summary',verbatimLicensed:false,...row.licensing};row.source={sourceType:'official-public-reference',lastVerified:null,effectiveDate:null,...row.source};row.corrections=Array.isArray(row.corrections)?row.corrections:[];row.sections=Array.isArray(row.sections)?row.sections:[];standards.push(Object.freeze(row));return row;}
function organization(id){return registries.get(key(id))||null;}
function list({species,registry,edition,status}={}){return standards.filter(s=>(!species||s.species===key(species))&&(!registry||s.registry===key(registry))&&(!edition||s.edition===edition)&&(!status||s.status===status)).map(clone);}
function resolve({species='Rabbit',registry='arba',breedId,breedName,edition,date}={}){const breed=key(breedId||breedName),rows=list({species,registry}).filter(s=>s.breedId===breed||key(s.breedName)===breed);if(edition)return rows.find(s=>s.edition===edition)||null;if(date){const t=String(date).slice(0,10);return rows.filter(s=>(!s.source.effectiveDate||s.source.effectiveDate<=t)&&(!s.source.expiresDate||s.source.expiresDate>=t)).sort((a,b)=>clean(b.source.effectiveDate).localeCompare(clean(a.source.effectiveDate)))[0]||null;}return rows.sort((a,b)=>clean(b.source.effectiveDate).localeCompare(clean(a.source.effectiveDate)))[0]||null;}
function applyCorrections(standard,date=new Date().toISOString().slice(0,10)){if(!standard)return null;const out=clone(standard);out.appliedCorrections=out.corrections.filter(c=>c.effectiveDate<=date).sort((a,b)=>a.effectiveDate.localeCompare(b.effectiveDate));return out;}
function search(query,{species='Rabbit',registry='arba',breedId='',global=false,limit=30}={}){const terms=clean(query).toLowerCase().split(/\s+/).filter(Boolean),contextBreed=key(breedId);if(!terms.length)return[];const rows=[];list({species,registry}).forEach(standard=>{standard.sections.forEach(section=>{const haystack=[standard.breedName,standard.edition,standard.status,section.type,section.title,section.summary,...(section.keywords||[]),...(section.varieties||[])].join(' ').toLowerCase();if(!terms.every(term=>haystack.includes(term)))return;let score=terms.reduce((n,t)=>n+(haystack.startsWith(t)?4:1),0);if(contextBreed&&standard.breedId===contextBreed)score+=global?2:20;if(contextBreed&&!global&&standard.breedId!==contextBreed)score-=5;rows.push({score,standardId:standard.id,registry:standard.registry,edition:standard.edition,breedId:standard.breedId,breedName:standard.breedName,status:standard.status,section:clone(section),source:clone(standard.source),licensing:clone(standard.licensing)});});});return rows.sort((a,b)=>b.score-a.score||a.breedName.localeCompare(b.breedName)).slice(0,limit);}
function unavailableState(error){return{available:false,title:'ARBA reference temporarily unavailable',message:'Your HerdHarbor show records are unaffected.',errorCode:error?'module-error':'no-data'};}
registerOrganization({id:'arba',name:'American Rabbit Breeders Association',species:'Rabbit',module:'Rabbit Resources',optional:true});
const edition='2026–2030';
const profiles=[
 ['holland-lop','Holland Lop',[['type','Type & body','Compact type and balance summary.',['body','type','balance']],['ear','Head, crown & ears','Breed-context summary for head, crown, ear carriage, and ear faults.',['head','crown','ear','fault']],['fur','Fur & condition','Breed-context fur and showroom-condition summary.',['fur','condition']],['dq','Faults and disqualifications','Structured reference index; consult the licensed current standard for exact judging language.',['fault','disqualification','dq']]]],
 ['rex','Rex',[['type','Type & body','Rex-specific body and type summary.',['body','type']],['fur','Rex fur','Rex-specific fur texture, density, and condition reference summary.',['fur','coat','texture']],['dq','Faults and disqualifications','Rex-context fault and DQ reference index.',['fault','disqualification','dq']]]],
 ['mini-rex','Mini Rex',[['type','Type & body','Mini Rex-specific compact type summary.',['body','type']],['fur','Mini Rex fur','Mini Rex-specific fur reference summary; never substituted for Rex criteria.',['fur','coat','texture']],['dq','Faults and disqualifications','Mini Rex-context fault and DQ reference index.',['fault','disqualification','dq']]]],
 ['netherland-dwarf','Netherland Dwarf',[['type','Type & body','Netherland Dwarf-specific type summary.',['body','type']],['head','Head & ears','Breed-context head and ear summary.',['head','ear','fault']],['dq','Faults and disqualifications','Netherland Dwarf-context fault and DQ reference index.',['fault','disqualification','dq']]]],
 ['english-spot','English Spot',[['marking','Markings','English Spot-specific marking and pattern reference summary.',['marking','pattern','chain','butterfly']],['type','Type & condition','Breed-context type and condition summary.',['body','type','condition']],['dq','Faults and disqualifications','English Spot-context fault and DQ reference index.',['fault','disqualification','dq']]]],
 ['lionhead','Lionhead',[['mane','Mane','Lionhead-specific mane and wool reference summary.',['mane','wool','coat']],['type','Type & head','Breed-context type and head summary.',['body','type','head']],['dq','Faults and disqualifications','Lionhead-context fault and DQ reference index.',['fault','disqualification','dq']]]]
];
profiles.forEach(([breedId,breedName,sections])=>registerStandard({registry:'arba',edition,species:'Rabbit',breedId,breedName,status:STATUS.RECOGNIZED,sections:sections.map(([type,title,summary,keywords])=>({id:`${breedId}:${type}`,type,title,summary,keywords})),classes:[],recognizedVarieties:[],showroomGroups:[],corrections:[],source:{sourceType:'official-public-reference',effectiveDate:'2026-01-01',expiresDate:'2030-12-31',lastVerified:'2026-08-31',citationRequired:true},licensing:{contentMode:'structured-summary',verbatimLicensed:false,notice:'Purchase or consult the current licensed ARBA Standard of Perfection for controlling language.'}}));
return Object.freeze({VERSION,STATUS,registerOrganization,registerStandard,organization,list,resolve,applyCorrections,search,unavailableState,key});
});
