const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),Base=require('../breeding-intelligence-core.js'),source=fs.readFileSync(path.join(root,'breeding-pair-hotfix-v1.4.1.js'),'utf8');
const elements=new Map(),document={readyState:'complete',body:{appendChild(el){if(el.id)elements.set(el.id,el)}},getElementById:id=>elements.get(id)||null,createElement:()=>({id:'',innerHTML:'',setAttribute(){},removeAttribute(){},getAttribute(){return null},querySelector(){return null},querySelectorAll(){return[]}}),querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){}};class MutationObserver{observe(){}}
const window={HerdHarborBreedingIntelligenceCore:Base};vm.runInNewContext(source,{window,document,MutationObserver,localStorage:{getItem(){return null},setItem(){}},console});const H=window.HerdHarborBreedingPairHotfix;assert.ok(H);assert.equal(H.version,'1.4.1');
assert.equal(H.canonicalSex('Male'),'male');assert.equal(H.canonicalSex('Female'),'female');assert.equal(H.canonicalSex('Buck'),'male');assert.equal(H.canonicalSex('Doe'),'female');
assert.equal(H.isPairingRabbit({species:'Rabbit',status:'Active'}),true);assert.equal(H.isPairingRabbit({species:'Rabbit',status:'Breeding'}),true);assert.equal(H.isPairingRabbit({species:'Rabbit',status:'Ancestor Only'}),false);assert.equal(H.isPairingRabbit({species:'Rabbit',status:'Sold'}),false);assert.equal(H.isPairingRabbit({species:'Rabbit',status:'Deceased'}),false);
for(const c of ['Black','Blue','Chocolate','Lilac','Black Magpie','Blue Magpie','Chocolate Magpie','Lilac Magpie','Black Harlequin','Chinchilla','Red Eyed White (REW)','Broken Black Magpie'])assert.ok(H.standardColors.includes(c),c);assert.ok(H.standardColors.length>=70);
const r=(id,name,color,sex,status='Active')=>({id,name,species:'Rabbit',color,sex,status}),bm=r('bm','BM','Black Magpie','Male'),bd=r('bd','BD','Blue Magpie','Female'),cb=r('cb','CB','Chocolate','Male'),ld=r('ld','LD','Lilac','Female');const mag=H.analyze(bm,bd),choc=H.analyze(cb,ld),names=x=>x.out.map(o=>o.name).sort();
assert.deepEqual(Array.from(mag.inputs),['Black Magpie','Blue Magpie']);assert.ok(names(mag).some(n=>/Magpie/.test(n)));assert.notDeepEqual(names(mag),names(choc));
bm.sireId='ancestor1';bd.damId='ancestor2';const before=names(H.analyze(bm,bd)),ancestor={id:'ancestor1',species:'Rabbit',status:'Ancestor Only',color:'REW'};ancestor.color='Lilac Tort';assert.deepEqual(before,names(H.analyze(bm,bd)));
const bad=H.analyze(r('u','Unknown','Mystery Custom Color','Male'),bd);assert.equal(bad.out.length,0);assert.equal(bad.bad.length,1);
assert.match(source,/input\[name="color"\]/);assert.match(source,/Ancestor colors: NOT used/);assert.match(source,/stopImmediatePropagation/);console.log('HerdHarbor v1.4.1 Pair Analysis hotfix tests passed');
