const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Core=require('../genetics-v2-phase1-core-v1.8.2.js');
function rec(alleles,source='breeder',status='confirmed',extra={}){return{alleles,source,status,...extra};}
function rabbit(id,color,loci={},extra={}){const genetics={loci:{}};for(const locus of Core.DISPLAY_LOCI)genetics.loci[locus]=rec(['_','_'],'','unknown');for(const [locus,value] of Object.entries(loci))genetics.loci[locus]=Array.isArray(value)?rec(value):value;return{id,name:id,species:'Rabbit',color,status:'Active',genetics,...extra};}
test('evidence hierarchy clearly separates proof from prediction',()=>{assert.equal(Core.evidenceTier({source:'genetic-test'}).label,'Confirmed by DNA');assert.equal(Core.evidenceTier({source:'offspring'}).label,'Proven by offspring');assert.ok(Core.evidenceStrength({source:'offspring'})>Core.evidenceStrength({source:'parent-inheritance'}));assert.ok(Core.evidenceStrength({source:'parent-inheritance'})>Core.evidenceStrength({source:'phenotype'}));assert.ok(Core.evidenceStrength({source:'phenotype'})>Core.evidenceStrength({source:'predicted'}));});
test('exact supported parent cross writes derived offspring genotype automatically',()=>{const dam=rabbit('dam','Black',{B:['B','B']}),sire=rabbit('sire','Chocolate',{B:['b','b']}),kit=rabbit('kit','',{B:rec(['_','_'],'','unknown')},{damId:'dam',sireId:'sire'});const result=Core.propagateState({animals:[dam,sire,kit]},'2026-09-07T23:10:00Z'),child=result.state.animals.find(a=>a.id==='kit');assert.deepEqual(child.genetics.loci.B.alleles,['B','b']);assert.equal(child.genetics.loci.B.source,'pedigree');assert.equal(child.genetics.loci.B.derivation,'parent-inheritance');const evidence=child.genetics.evidence.find(e=>e.id==='gv2p1:inherit:kit:B');assert.equal(evidence.supported,true);assert.deepEqual(evidence.possibleGenotypes,[{genotype:'B/b',probability:1}]);});
test('multi-outcome parent cross stays predicted instead of guessing a genotype',()=>{const dam=rabbit('dam','Black',{D:['D','d']}),sire=rabbit('sire','Black',{D:['D','d']}),kit=rabbit('kit','',{D:rec(['_','_'],'','unknown')},{damId:'dam',sireId:'sire'});const result=Core.propagateState({animals:[dam,sire,kit]},'2026-09-07T23:10:00Z'),child=result.state.animals.find(a=>a.id==='kit'),evidence=child.genetics.evidence.find(e=>e.id==='gv2p1:inherit:kit:D');assert.deepEqual(child.genetics.loci.D.alleles,['_','_']);assert.equal(evidence.status,'predicted');assert.deepEqual(Object.fromEntries(evidence.possibleGenotypes.map(x=>[x.genotype,x.probability])),{'D/d':.5,'D/D':.25,'d/d':.25});});
test('blue offspring proves dilute allele and can resolve black parents as D/d',()=>{const dam=rabbit('dam','Black',{D:rec(['_','_'],'','unknown')}),sire=rabbit('sire','Black',{D:rec(['_','_'],'','unknown')}),kit=rabbit('kit','Blue',{}, {damId:'dam',sireId:'sire'});const result=Core.propagateState({animals:[dam,sire,kit]},'2026-09-07T23:10:00Z');for(const id of ['dam','sire']){const parent=result.state.animals.find(a=>a.id===id);assert.deepEqual(parent.genetics.loci.D.alleles,['D','d']);assert.equal(parent.genetics.loci.D.source,'offspring');assert.ok(parent.genetics.evidence.some(e=>e.kind==='offspring-proof'&&e.locus==='D'));}});
test('BEW offspring proves V/v in each non-BEW parent',()=>{const dam=rabbit('dam','Black',{V:rec(['_','_'],'','unknown')}),sire=rabbit('sire','Black',{V:rec(['_','_'],'','unknown')}),kit=rabbit('kit','Blue-Eyed White (BEW)',{}, {damId:'dam',sireId:'sire'});const result=Core.propagateState({animals:[dam,sire,kit]},'2026-09-07T23:10:00Z');assert.deepEqual(result.state.animals.find(a=>a.id==='dam').genetics.loci.V.alleles,['V','v']);assert.deepEqual(result.state.animals.find(a=>a.id==='sire').genetics.loci.V.alleles,['V','v']);});
test('strong contradictory evidence is retained and surfaced as a conflict',()=>{const dam=rabbit('dam','Black',{D:['D','D']}),sire=rabbit('sire','Black',{D:['D','D']}),kit=rabbit('kit','Blue',{D:rec(['d','d'],'genetic-test','confirmed')},{damId:'dam',sireId:'sire'});const result=Core.propagateState({animals:[dam,sire,kit]},'2026-09-07T23:10:00Z'),child=result.state.animals.find(a=>a.id==='kit');assert.deepEqual(child.genetics.loci.D.alleles,['d','d']);assert.equal(child.genetics.loci.D.source,'genetic-test');assert.ok(child.genetics.conflicts.some(c=>c.locus==='D'&&c.incomingSource==='parent-inheritance'));assert.ok(result.state.animals.find(a=>a.id==='dam').genetics.conflicts.some(c=>c.incomingSource==='offspring'));});
test('propagation is idempotent and does not cause cloud sync churn',()=>{const dam=rabbit('dam','Black',{B:['B','B']}),sire=rabbit('sire','Chocolate',{B:['b','b']}),kit=rabbit('kit','',{B:rec(['_','_'],'','unknown')},{damId:'dam',sireId:'sire'});const first=Core.propagateState({animals:[dam,sire,kit]},'2026-09-07T23:10:00Z');assert.ok(first.changed>0);const snapshot=JSON.stringify(first.state),second=Core.propagateState(first.state,'2026-09-07T23:15:00Z');assert.equal(second.changed,0);assert.strictEqual(second.state,first.state);assert.equal(JSON.stringify(second.state),snapshot);});
test('non-rabbit records are untouched',()=>{const calf={id:'c1',species:'Cattle',damId:'cow',sireId:'bull',genetics:{loci:{B:{alleles:['B','B']}}}};assert.equal(Core.propagateState({animals:[calf]}).changed,0);});
test('runtime and build contract expose Genetics V2 phase 1 under the promoted v1.8.2 release identity',()=>{const root=path.resolve(__dirname,'..'),runtime=fs.readFileSync(path.join(root,'genetics-v2-phase1-v1.8.2.js'),'utf8'),css=fs.readFileSync(path.join(root,'genetics-v2-phase1-v1.8.2.css'),'utf8'),build=fs.readFileSync(path.join(root,'herdharbor-build.js'),'utf8'),sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');assert.match(runtime,/HerdHarborGeneticsV2Phase1Core/);assert.match(runtime,/herdharbor:offspring-auto-created/);assert.match(runtime,/data-hh-p2-panel=\"genetics\"/);assert.match(runtime,/Prediction stays prediction/);assert.match(css,/hh-gv2-panel/);assert.match(build,/genetics-v2-phase1-core-v1\.8\.2\.js\?v=1/);assert.match(build,/genetics-v2-phase1-v1\.8\.2\.js\?v=1/);assert.match(build,/genetics-v2-phase1-v1\.8\.2\.css\?v=1/);assert.match(build,/version: "1\.8\.2"/);assert.doesNotMatch(build,/version: "1\.8\.1"/);assert.match(sw,/genetics-v2-phase1-core-v1\.8\.2\.js/);});