"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), "utf8");

const html = read("index.html");
const manifest = JSON.parse(read("manifest.json"));
const twa = JSON.parse(read("twa-manifest.json"));
const appGradle = read("android/app/build.gradle");
const worker = read("service-worker.js");
const pwa = read("pwa.js");
const shows = read("shows-v1.5.1.js");
const hardening = read("shows-v1.5.1-hardening.js");
const title = read("google-play/listing/en-US/title.txt").trim();
const shortDescription = read("google-play/listing/en-US/short-description.txt").trim();
const fullDescription = read("google-play/listing/en-US/full-description.txt").trim();
const androidManifest = read("android/app/src/main/AndroidManifest.xml");

assert.doesNotMatch(html, /pre[ -]?alpha/i);
assert.equal(manifest.version, "1.5.1");
assert.equal(manifest.display, "standalone");
assert.ok(manifest.shortcuts.some((shortcut) => shortcut.url === "./#shows"));
assert.equal(twa.packageId, "com.ebrllc.herdharbor");
assert.equal(twa.appVersion, "1.5.1");
assert.equal(twa.appVersionCode, 9);
assert.equal(twa.host, "app.herdharbor.com");
assert.match(appGradle, /applicationId:\s*'com\.ebrllc\.herdharbor'/);
assert.match(appGradle, /namespace "com\.ebrllc\.herdharbor"/);
assert.match(appGradle, /applicationId "com\.ebrllc\.herdharbor"/);
assert.match(appGradle, /compileSdkVersion 36/);
assert.match(appGradle, /targetSdkVersion 36/);
assert.match(appGradle, /versionCode 9/);
assert.match(appGradle, /versionName "1\.5\.1"/);
assert.match(appGradle, /https:\/\/app\.herdharbor\.com\/manifest\.json/);
assert.match(worker, /v1\.5\.1-alpha-stability-membership-review-2/);
assert.match(worker, /rabbit-records-v1\.5\.1\.js\?v=1\.4\.5/);
assert.match(worker, /pedigree-genetics-v1\.5\.1\.js\?v=1\.4\.5/);
assert.match(worker, /shows-v1\.5\.1\.css\?v=1\.5\.0/);
assert.match(worker, /shows-v1\.5\.1\.js\?v=1\.5\.0/);
assert.match(worker, /shows-v1\.5\.1-hardening\.js\?v=1\.5\.0/);
assert.match(pwa, /\$\{APP_VERSION\}-alpha-stability-\$\{BUILD_ID\}/);
assert.match(pwa, /const BUILD_ID = "membership-review-2"/);
assert.match(pwa, /loadPedigreeVisuals/);
assert.match(pwa, /loadBreedingIntelligence/);
assert.match(pwa, /loadShows/);
assert.match(pwa, /shows-v1\.5\.1-hardening\.js\?v=1\.5\.0/);
assert.match(pwa, /registration\.update\(\)/);
assert.doesNotMatch(pwa, /HerdHarborCloud/);
assert.match(shows, /const VERSION='1\.5\.0'/);
assert.match(shows, /state\.transactions\.push/);
assert.match(shows, /state\.health\.push/);
assert.match(hardening, /PAGE_SIZE = 24/);
assert.match(androidManifest, /package="com\.ebrllc\.herdharbor"/);
assert.match(androidManifest, /android:allowBackup="false"/);
assert.match(androidManifest, /android:usesCleartextTraffic="false"/);
assert.ok(fs.existsSync(path.join(root, "android/app/src/main/java/com/ebrllc/herdharbor/Application.java")));
assert.ok(fs.existsSync(path.join(root, "android/app/src/main/java/com/ebrllc/herdharbor/DelegationService.java")));
assert.ok(fs.existsSync(path.join(root, "android/app/src/main/java/com/ebrllc/herdharbor/LauncherActivity.java")));
assert.ok(!fs.existsSync(path.join(root, "android/app/src/main/java/com/herdharbor/app/Application.java")));
assert.ok(fs.existsSync(path.join(root, "pedigree-genetics-v1.5.1.js")));
assert.ok(fs.existsSync(path.join(root, "pedigree-genetics-v1.5.1.css")));
assert.ok(fs.existsSync(path.join(root, "shows-v1.5.1.js")));
assert.ok(fs.existsSync(path.join(root, "shows-v1.5.1.css")));
assert.ok(fs.existsSync(path.join(root, "shows-v1.5.1-hardening.js")));
assert.ok(title.length <= 30, "Play title must be 30 characters or fewer");
assert.ok(shortDescription.length <= 80, "Play short description must be 80 characters or fewer");
assert.ok(fullDescription.length <= 4000, "Play full description must be 4,000 characters or fewer");
assert.ok(fs.statSync(path.join(root, "android/store_icon.png")).size <= 1024 * 1024);
assert.ok(fs.existsSync(path.join(root, "google-play/assets/app-icon-512.png")));
assert.ok(fs.existsSync(path.join(root, "google-play/assets/feature-graphic-1024x500.png")));

console.log("Google Play Alpha v1.5.1 membership and stability readiness tests passed");
