"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const build = fs.readFileSync(path.join(root, "herdharbor-build.js"), "utf8");
const pwa = fs.readFileSync(path.join(root, "pwa.js"), "utf8");
const manifest = fs.readFileSync(path.join(root, "manifest.json"), "utf8");

assert.match(build, /hh-mobile-pwa-install-entry/, "mobile web gets a visible install entry point");
assert.match(build, /data\.pwaInstall|dataset\.pwaInstall/, "install entry connects to the canonical PWA install action");
assert.match(build, /Add to Home Screen/, "iOS users get Add to Home Screen guidance");
assert.match(build, /Install HerdHarbor/, "install-capable mobile browsers get an install label");
assert.match(build, /display-mode: standalone/, "installed standalone mode suppresses the web install entry");
assert.match(build, /max-width: 900px/, "the install entry is scoped to mobile-sized web layouts");
assert.match(pwa, /beforeinstallprompt/, "canonical PWA controller still captures the browser install prompt");
assert.match(pwa, /HerdHarborPWA\s*=\s*\{/, "canonical PWA controller exposes its install action");
const parsed = JSON.parse(manifest);
assert.equal(parsed.display, "standalone", "manifest remains installable as a standalone PWA");
assert.ok(Array.isArray(parsed.icons) && parsed.icons.some(icon => icon.sizes === "192x192") && parsed.icons.some(icon => icon.sizes === "512x512"), "manifest retains installable app icons");
console.log("Mobile PWA install entry contract passed");
