const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const source = fs.readFileSync("subscription-engine-v1.8.0.js", "utf8");
function loadEngine(){const document={readyState:"loading",documentElement:{dataset:{},classList:{add(){},remove(){}}},addEventListener(){},dispatchEvent(){},getElementById(){return null},querySelector(){return null},querySelectorAll(){return[]},visibilityState:"hidden"};const localStorage={length:0,getItem(){return null},setItem(){},key(){return null}};const window={document,localStorage,setTimeout,clearTimeout,setInterval(){return 1},clearInterval(){},addEventListener(){},getComputedStyle(){return{display:"none",visibility:"hidden"}},HerdHarborRelease:{plans:{junior:{label:"Junior",priceMonthly:0,maxActiveAnimals:5},founder:{label:"Founder",priceMonthly:7.99},member:{label:"Member",priceMonthly:14.99},business:{label:"Business",priceMonthly:49.99}}}};window.window=window;const context=vm.createContext({window,document,localStorage,CustomEvent:class CustomEvent{constructor(name,options){this.type=name;this.detail=options?.detail}},MutationObserver:class MutationObserver{observe(){} disconnect(){}},Intl,URL,Date,Number,Math,JSON,String,Set,Object,Array,Boolean,console,structuredClone});vm.runInContext(source,context,{filename:"subscription-engine-v1.8.0.js"});return window.HerdHarborSubscriptionEngine}
test("v1.8.0 subscription engine remains standalone",()=>{const e=loadEngine();assert.equal(e.version,"1.8.0");assert.equal(typeof e.configureProvider,"function");assert.equal(typeof e.runDiagnostics,"function");assert.equal(typeof e.open,"function")});
test("normalization accepts only known plans and safe status fields",()=>{const r=loadEngine().__test.normalizeState({plan:"MEMBER",status:"ACTIVE",priceCents:1499.4,billingInterval:"year",referral:{successfulReferrals:5.9}});assert.equal(r.plan,"member");assert.equal(r.status,"active");assert.equal(r.priceCents,1499);assert.equal(r.billingInterval,"year");assert.equal(r.referral.successfulReferrals,5)});
test("unknown plan does not become an entitlement",()=>assert.equal(loadEngine().__test.normalizeState({plan:"super-admin"}).plan,null));
test("referral milestones match HerdHarbor v1.8.0 rules",()=>{const e=loadEngine(),four=e.referralProjection(4),five=e.referralProjection(5),twenty=e.referralProjection(20);assert.equal(four.achieved.length,0);assert.equal(four.next.threshold,5);assert.equal(four.next.remaining,1);assert.equal(five.achieved[0].freeMonths,1);assert.equal(five.next.threshold,20);assert.equal(twenty.achieved.length,2);assert.equal(twenty.next,null)});
test("engine never aliases the legacy billing namespace",()=>{assert.match(source,/window\.HerdHarborSubscriptionEngine/);assert.doesNotMatch(source,/window\.HerdHarborBilling\s*=/)});
test("engine does not collect raw payment credentials",()=>{assert.doesNotMatch(source,/cardNumber\s*[:=]/i);assert.doesNotMatch(source,/cvc\s*[:=]/i);assert.doesNotMatch(source,/cvv\s*[:=]/i);assert.doesNotMatch(source,/stripeSecret\s*[:=]/i)});
test("subscription nav uses an isolated attribute rather than native app routing",()=>{assert.match(source,/data-hh-subscription-engine-tab/);assert.doesNotMatch(source,/data-route=["']subscription["']/)});
test("v1.8.1 build preserves and bootstraps the standalone v1.8.0 engine",()=>{const b=fs.readFileSync("herdharbor-build.js","utf8");assert.match(b,/version:\s*"1\.8\.1"/);assert.match(b,/subscription-launch-v1\.8\.1\.js\?v=1/);assert.match(b,/subscription-engine-v1\.8\.0\.js\?v=1/);assert.match(b,/subscription-engine-v1\.8\.0\.css\?v=1/)});
test("legacy billing remains disabled while v1.8.1 launch policy owns rollout",()=>assert.match(fs.readFileSync("herdharbor-release-v1.6.1.js","utf8"),/billingEnabled:\s*false/));
test("v1.8.1 service worker rolls the shell and keeps subscription assets network-first",()=>{const w=fs.readFileSync("service-worker.js","utf8");assert.match(w,/herdharbor-shell-v1\.8\.1/);assert.match(w,/"\.\/subscription-launch-v1\.8\.1\.js\?v=1"/);assert.match(w,/"\/subscription-launch-v1\.8\.1\.js"/);assert.match(w,/"\.\/subscription-engine-v1\.8\.0\.js\?v=1"/);assert.match(w,/"\/subscription-engine-v1\.8\.0\.js"/);assert.match(w,/"\/subscription-engine-v1\.8\.0\.css"/)});
test("subscription header presentation is member-facing and cache-busted",()=>{const h=fs.readFileSync("subscription-header-copy-v1.8.0.js","utf8");const b=fs.readFileSync("herdharbor-build.js","utf8");const w=fs.readFileSync("service-worker.js","utf8");assert.match(h,/Manage your plan, billing, referral rewards, and subscription credits\./);assert.match(h,/textContent !== "Subscriptions"/);assert.match(h,/Your subscription and billing are ready to manage\./);assert.match(b,/subscription-header-copy-v1\.8\.0\.js\?v=3/);assert.match(w,/subscription-header-copy-v1\.8\.0\.js\?v=3/);assert.match(w,/october-subscription-launch-referrals-credits-4/)});
